using Beamable.Api.Autogenerated.Models;

namespace Beamable
{
	public static class OpenApiExtensions
	{
		public static bool IsUsingBeamableNotifications(this RealmsBasicRealmConfiguration config)
		{
			// "pubnub" is the only other valid option besides using beamable notifications.
			//  thus, if the string is pubnub, we aren't using beam notifs...
			//  and opposite, if the string is NOT pubnub, then the only other option is beamable notifs
			return config?.websocketConfig?.provider != "pubnub";
		}

		public static bool IsUsingPubnubNotifications(this RealmsBasicRealmConfiguration config) =>
			!IsUsingBeamableNotifications(config);
	}
}
