dist:
  name: beamable-collector
  description: Beamable Otel Collector distribution
  output_path: ./beamable-collector

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.122.1
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.122.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhouseexporter v0.122.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.122.1

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.122.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.122.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0