# All environment variables here are coming from either the C#MS or the Beamable CLI. any changes in it's default values should be changed in those sources
# Default values:
# BEAM_CLICKHOUSE_PROCESSOR_TIMEOUT=5s
# BEAM_CLICKHOUSE_PROCESSOR_BATCH_SIZE=5000
# BEAM_CLICKHOUSE_EXPORTER_TIMEOUT=5s
# BEAM_CLICKHOUSE_EXPORTER_QUEUE_SIZE=1000
# BEAM_CLICKHOUSE_EXPORTER_RETRY_ENABLED=true
# BEAM_CLICKHOUSE_EXPORTER_RETRY_INITIAL_INTERVAL=5s
# BEAM_CLICKHOUSE_EXPORTER_RETRY_MAX_INTERVAL=30s
# BEAM_CLICKHOUSE_EXPORTER_RETRY_MAX_ELAPSED_TIME=300s

receivers:
  filelog:
    include:
      - /opt/data/logs/access-structured.log
    start_at: beginning
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.time_local
          layout: '%Y-%m-%d %H:%M:%S'
  otlp:
    protocols:
      http:
        endpoint: ${env:BEAM_OTLP_HTTP_ENDPOINT}
processors:
  batch:
    timeout: ${env:BEAM_CLICKHOUSE_PROCESSOR_TIMEOUT}
    send_batch_size: ${env:BEAM_CLICKHOUSE_PROCESSOR_BATCH_SIZE}
exporters:
  # debug: Uncomment this if wanting to debug all values flowing to the collector, printing the information in the console
  #   verbosity: detailed
  #   sampling_initial: 2
  #   sampling_thereafter: 500
  clickhouse:
    endpoint: ${env:BEAM_CLICKHOUSE_ENDPOINT}
    username: ${env:BEAM_CLICKHOUSE_USERNAME}
    password: ${env:BEAM_CLICKHOUSE_PASSWORD}
    traces_table_name: otel_traces
    logs_table_name: otel_logs
    timeout: ${env:BEAM_CLICKHOUSE_EXPORTER_TIMEOUT}
    database: default
    create_schema: false
    sending_queue:
      queue_size: ${env:BEAM_CLICKHOUSE_EXPORTER_QUEUE_SIZE}
    retry_on_failure:
      enabled: ${env:BEAM_CLICKHOUSE_EXPORTER_RETRY_ENABLED}
      initial_interval: ${env:BEAM_CLICKHOUSE_EXPORTER_RETRY_INITIAL_INTERVAL}
      max_interval: ${env:BEAM_CLICKHOUSE_EXPORTER_RETRY_MAX_INTERVAL}
      max_elapsed_time: ${env:BEAM_CLICKHOUSE_EXPORTER_RETRY_MAX_ELAPSED_TIME}
    metrics_tables:
      gauge: 
        name: "otel_metrics_gauge"
      sum: 
        name: "otel_metrics_sum"
      summary: 
        name: "otel_metrics_summary"
      histogram: 
        name: "otel_metrics_histogram"
      exponential_histogram: 
        name: "otel_metrics_exp_histogram"
extensions:
  servicediscovery:
    discovery_port: ${env:BEAM_COLLECTOR_DISCOVERY_PORT}
    discovery_delay: 100 #this is in milliseconds

service:
  extensions: [servicediscovery]
  telemetry:
    metrics:
      level: normal
      readers:
        - pull:
            exporter:
              prometheus:
                host: 127.0.0.1
                port: ${env:BEAM_COLLECTOR_PROMETHEUS_PORT} # This is to disable Prometheus from binds to a port and not enable multiple running collectors
    # logs:
    #   level: "debug" #Uncomment this to test collector with more verbose logs
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse] #add "debug" here to enable debug for metrics