// This file generated by a copy-operation from another project. 
// Edits to this file will be overwritten by the build process. 


namespace Beamable.Api.Autogenerated.Zones
{
    using Beamable.Api.Autogenerated.Models;
    using Beamable.Common.Content;
    using Beamable.Common;
    using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
    using Method = Beamable.Common.Api.Method;
    using Beamable.Common.Dependencies;
    
    public partial interface IBeamZonesApi
    {
        /// <summary>
        /// List all forced bundles scoped to a zone. Independent of realm entries.
        /// 
        /// GET call to `/api/beamo/zones/{customerId}/{zoneId}/forced-bundles` endpoint.
        /// </summary>
        /// <param name="customerId"></param>
        /// <param name="zoneId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="ListForcedBundlesResponse"/></returns>
        Promise<ListForcedBundlesResponse> GetZonesForcedBundles(string customerId, string zoneId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// Set or update a per-zone forced bundle. Independent of realm entries.
        /// 
        /// PUT call to `/api/beamo/zones/{customerId}/{zoneId}/forced-bundles/{ns}/{bundleName}` endpoint.
        /// </summary>
        /// <param name="bundleName"></param>
        /// <param name="customerId"></param>
        /// <param name="ns"></param>
        /// <param name="zoneId"></param>
        /// <param name="gsReq">The <see cref="SetForcedBundleRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="ApiBeamoZonesForcedBundlesPutZonesResponse"/></returns>
        Promise<ApiBeamoZonesForcedBundlesPutZonesResponse> PutZonesForcedBundles(string bundleName, string customerId, string ns, string zoneId, SetForcedBundleRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// Remove a per-zone forced bundle.
        /// 
        /// DELETE call to `/api/beamo/zones/{customerId}/{zoneId}/forced-bundles/{ns}/{bundleName}` endpoint.
        /// </summary>
        /// <param name="bundleName"></param>
        /// <param name="customerId"></param>
        /// <param name="ns"></param>
        /// <param name="zoneId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="ApiBeamoZonesForcedBundlesDeleteZonesResponse"/></returns>
        Promise<ApiBeamoZonesForcedBundlesDeleteZonesResponse> DeleteZonesForcedBundles(string bundleName, string customerId, string ns, string zoneId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// List the zones of a customer that are visible to the caller. Customer-level
        ///Admins see every zone; other callers only see zones on which their effective
        ///zone role is at least Tester.
        /// 
        /// GET call to `/api/customers/{customerId}/zones` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer.</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="ZonesResponse"/></returns>
        Promise<ZonesResponse> GetZones(string customerId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// Create a new zone under a customer.
        /// 
        /// POST call to `/api/customers/{customerId}/zones` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer to create the zone under.</param>
        /// <param name="gsReq">The <see cref="CreateZoneRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="ZoneView"/></returns>
        Promise<ZoneView> PostZones(string customerId, CreateZoneRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// Get a specific zone by customer and zone ID.
        /// 
        /// GET call to `/api/customers/{customerId}/zones/{zoneId}` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer.</param>
        /// <param name="zoneId">ID of the zone to retrieve.</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="ZoneView"/></returns>
        Promise<ZoneView> GetZones(string customerId, string zoneId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// Archive (soft-delete) a zone. Blocked while any realm is bound to the zone.
        /// 
        /// DELETE call to `/api/customers/{customerId}/zones/{zoneId}` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer that owns the zone.</param>
        /// <param name="zoneId">ID of the zone to archive.</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyMessage"/></returns>
        Promise<EmptyMessage> DeleteZones(string customerId, string zoneId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// Rename a zone.
        /// 
        /// PUT call to `/api/customers/{customerId}/zones/{zoneId}/rename` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer that owns the zone.</param>
        /// <param name="zoneId">ID of the zone to rename.</param>
        /// <param name="gsReq">The <see cref="RenameZoneRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyMessage"/></returns>
        Promise<EmptyMessage> PutZonesRename(string customerId, string zoneId, RenameZoneRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// Set the zone-scoped role of an account.
        /// 
        /// PUT call to `/api/customers/{customerId}/zones/{zoneId}/roles/{accountId}` endpoint.
        /// </summary>
        /// <param name="accountId">ID of the account to grant the role to.</param>
        /// <param name="customerId">ID of the customer that owns the zone.</param>
        /// <param name="zoneId">ID of the zone the role is scoped to.</param>
        /// <param name="gsReq">The <see cref="SetZoneRoleRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyMessage"/></returns>
        Promise<EmptyMessage> PutZonesRoles(string accountId, string customerId, string zoneId, SetZoneRoleRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// Remove the zone-scoped role of an account. The zone's default role (if any)
        ///applies afterwards.
        /// 
        /// DELETE call to `/api/customers/{customerId}/zones/{zoneId}/roles/{accountId}` endpoint.
        /// </summary>
        /// <param name="accountId">ID of the account to remove the role from.</param>
        /// <param name="customerId">ID of the customer that owns the zone.</param>
        /// <param name="zoneId">ID of the zone the role is scoped to.</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyMessage"/></returns>
        Promise<EmptyMessage> DeleteZonesRoles(string accountId, string customerId, string zoneId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// Bind a realm to a zone, or unbind it when no zone ID is given. A realm has at
        ///most one zone and defaults to none.
        /// 
        /// PUT call to `/api/customers/{customerId}/realms/{realmId}/zone` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer.</param>
        /// <param name="realmId">ID of the realm to bind.</param>
        /// <param name="gsReq">The <see cref="SetRealmZoneRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyMessage"/></returns>
        Promise<EmptyMessage> PutRealmsZone(string customerId, string realmId, SetRealmZoneRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// Promote the current Beamo manifest from a source zone into the destination zone.
        ///Zones promote microservices only (no content).
        /// 
        /// POST call to `/api/customers/{customerId}/zones/{zoneId}/promotion` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer.</param>
        /// <param name="zoneId">ID of the zone to promote into.</param>
        /// <param name="gsReq">The <see cref="PromoteZoneRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="PromoteZoneResponse"/></returns>
        Promise<PromoteZoneResponse> PostZonesPromotion(string customerId, string zoneId, PromoteZoneRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// Preview what a zone→zone promotion would change, without applying it.
        /// 
        /// GET call to `/api/customers/{customerId}/zones/{zoneId}/promotion` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer.</param>
        /// <param name="sourceZoneId">ID of the source zone.</param>
        /// <param name="zoneId">ID of the destination zone.</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="PromoteZoneResponse"/></returns>
        Promise<PromoteZoneResponse> GetZonesPromotion(string customerId, string zoneId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> sourceZoneId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
    }
    public partial class BeamZonesApi : IBeamZonesApi
    {
        /// <summary>
        /// List all forced bundles scoped to a zone. Independent of realm entries.
        /// 
        /// GET call to `/api/beamo/zones/{customerId}/{zoneId}/forced-bundles` endpoint.
        /// </summary>
        /// <param name="customerId"></param>
        /// <param name="zoneId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="ListForcedBundlesResponse"/></returns>
        public virtual Promise<ListForcedBundlesResponse> GetZonesForcedBundles(string customerId, string zoneId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/beamo/zones/{customerId}/{zoneId}/forced-bundles";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            gsUrl = gsUrl.Replace("{zoneId}", _requester.EscapeURL(zoneId.ToString()));
            // make the request and return the result
            return _requester.Request<ListForcedBundlesResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<ListForcedBundlesResponse>);
        }
        /// <summary>
        /// Set or update a per-zone forced bundle. Independent of realm entries.
        /// 
        /// PUT call to `/api/beamo/zones/{customerId}/{zoneId}/forced-bundles/{ns}/{bundleName}` endpoint.
        /// </summary>
        /// <param name="bundleName"></param>
        /// <param name="customerId"></param>
        /// <param name="ns"></param>
        /// <param name="zoneId"></param>
        /// <param name="gsReq">The <see cref="SetForcedBundleRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="ApiBeamoZonesForcedBundlesPutZonesResponse"/></returns>
        public virtual Promise<ApiBeamoZonesForcedBundlesPutZonesResponse> PutZonesForcedBundles(string bundleName, string customerId, string ns, string zoneId, SetForcedBundleRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/beamo/zones/{customerId}/{zoneId}/forced-bundles/{ns}/{bundleName}";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            gsUrl = gsUrl.Replace("{zoneId}", _requester.EscapeURL(zoneId.ToString()));
            gsUrl = gsUrl.Replace("{ns}", _requester.EscapeURL(ns.ToString()));
            gsUrl = gsUrl.Replace("{bundleName}", _requester.EscapeURL(bundleName.ToString()));
            // make the request and return the result
            return _requester.Request<ApiBeamoZonesForcedBundlesPutZonesResponse>(Method.PUT, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, this.Serialize<ApiBeamoZonesForcedBundlesPutZonesResponse>);
        }
        /// <summary>
        /// Remove a per-zone forced bundle.
        /// 
        /// DELETE call to `/api/beamo/zones/{customerId}/{zoneId}/forced-bundles/{ns}/{bundleName}` endpoint.
        /// </summary>
        /// <param name="bundleName"></param>
        /// <param name="customerId"></param>
        /// <param name="ns"></param>
        /// <param name="zoneId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="ApiBeamoZonesForcedBundlesDeleteZonesResponse"/></returns>
        public virtual Promise<ApiBeamoZonesForcedBundlesDeleteZonesResponse> DeleteZonesForcedBundles(string bundleName, string customerId, string ns, string zoneId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/beamo/zones/{customerId}/{zoneId}/forced-bundles/{ns}/{bundleName}";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            gsUrl = gsUrl.Replace("{zoneId}", _requester.EscapeURL(zoneId.ToString()));
            gsUrl = gsUrl.Replace("{ns}", _requester.EscapeURL(ns.ToString()));
            gsUrl = gsUrl.Replace("{bundleName}", _requester.EscapeURL(bundleName.ToString()));
            // make the request and return the result
            return _requester.Request<ApiBeamoZonesForcedBundlesDeleteZonesResponse>(Method.DELETE, gsUrl, default(object), includeAuthHeader, this.Serialize<ApiBeamoZonesForcedBundlesDeleteZonesResponse>);
        }
        /// <summary>
        /// List the zones of a customer that are visible to the caller. Customer-level
        ///Admins see every zone; other callers only see zones on which their effective
        ///zone role is at least Tester.
        /// 
        /// GET call to `/api/customers/{customerId}/zones` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer.</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="ZonesResponse"/></returns>
        public virtual Promise<ZonesResponse> GetZones(string customerId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/customers/{customerId}/zones";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            // make the request and return the result
            return _requester.Request<ZonesResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<ZonesResponse>);
        }
        /// <summary>
        /// Create a new zone under a customer.
        /// 
        /// POST call to `/api/customers/{customerId}/zones` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer to create the zone under.</param>
        /// <param name="gsReq">The <see cref="CreateZoneRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="ZoneView"/></returns>
        public virtual Promise<ZoneView> PostZones(string customerId, CreateZoneRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/customers/{customerId}/zones";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            // make the request and return the result
            return _requester.Request<ZoneView>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, this.Serialize<ZoneView>);
        }
        /// <summary>
        /// Get a specific zone by customer and zone ID.
        /// 
        /// GET call to `/api/customers/{customerId}/zones/{zoneId}` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer.</param>
        /// <param name="zoneId">ID of the zone to retrieve.</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="ZoneView"/></returns>
        public virtual Promise<ZoneView> GetZones(string customerId, string zoneId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/customers/{customerId}/zones/{zoneId}";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            gsUrl = gsUrl.Replace("{zoneId}", _requester.EscapeURL(zoneId.ToString()));
            // make the request and return the result
            return _requester.Request<ZoneView>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<ZoneView>);
        }
        /// <summary>
        /// Archive (soft-delete) a zone. Blocked while any realm is bound to the zone.
        /// 
        /// DELETE call to `/api/customers/{customerId}/zones/{zoneId}` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer that owns the zone.</param>
        /// <param name="zoneId">ID of the zone to archive.</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyMessage"/></returns>
        public virtual Promise<EmptyMessage> DeleteZones(string customerId, string zoneId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/customers/{customerId}/zones/{zoneId}";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            gsUrl = gsUrl.Replace("{zoneId}", _requester.EscapeURL(zoneId.ToString()));
            // make the request and return the result
            return _requester.Request<EmptyMessage>(Method.DELETE, gsUrl, default(object), includeAuthHeader, this.Serialize<EmptyMessage>);
        }
        /// <summary>
        /// Rename a zone.
        /// 
        /// PUT call to `/api/customers/{customerId}/zones/{zoneId}/rename` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer that owns the zone.</param>
        /// <param name="zoneId">ID of the zone to rename.</param>
        /// <param name="gsReq">The <see cref="RenameZoneRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyMessage"/></returns>
        public virtual Promise<EmptyMessage> PutZonesRename(string customerId, string zoneId, RenameZoneRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/customers/{customerId}/zones/{zoneId}/rename";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            gsUrl = gsUrl.Replace("{zoneId}", _requester.EscapeURL(zoneId.ToString()));
            // make the request and return the result
            return _requester.Request<EmptyMessage>(Method.PUT, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, this.Serialize<EmptyMessage>);
        }
        /// <summary>
        /// Set the zone-scoped role of an account.
        /// 
        /// PUT call to `/api/customers/{customerId}/zones/{zoneId}/roles/{accountId}` endpoint.
        /// </summary>
        /// <param name="accountId">ID of the account to grant the role to.</param>
        /// <param name="customerId">ID of the customer that owns the zone.</param>
        /// <param name="zoneId">ID of the zone the role is scoped to.</param>
        /// <param name="gsReq">The <see cref="SetZoneRoleRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyMessage"/></returns>
        public virtual Promise<EmptyMessage> PutZonesRoles(string accountId, string customerId, string zoneId, SetZoneRoleRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/customers/{customerId}/zones/{zoneId}/roles/{accountId}";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            gsUrl = gsUrl.Replace("{zoneId}", _requester.EscapeURL(zoneId.ToString()));
            gsUrl = gsUrl.Replace("{accountId}", _requester.EscapeURL(accountId.ToString()));
            // make the request and return the result
            return _requester.Request<EmptyMessage>(Method.PUT, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, this.Serialize<EmptyMessage>);
        }
        /// <summary>
        /// Remove the zone-scoped role of an account. The zone's default role (if any)
        ///applies afterwards.
        /// 
        /// DELETE call to `/api/customers/{customerId}/zones/{zoneId}/roles/{accountId}` endpoint.
        /// </summary>
        /// <param name="accountId">ID of the account to remove the role from.</param>
        /// <param name="customerId">ID of the customer that owns the zone.</param>
        /// <param name="zoneId">ID of the zone the role is scoped to.</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyMessage"/></returns>
        public virtual Promise<EmptyMessage> DeleteZonesRoles(string accountId, string customerId, string zoneId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/customers/{customerId}/zones/{zoneId}/roles/{accountId}";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            gsUrl = gsUrl.Replace("{zoneId}", _requester.EscapeURL(zoneId.ToString()));
            gsUrl = gsUrl.Replace("{accountId}", _requester.EscapeURL(accountId.ToString()));
            // make the request and return the result
            return _requester.Request<EmptyMessage>(Method.DELETE, gsUrl, default(object), includeAuthHeader, this.Serialize<EmptyMessage>);
        }
        /// <summary>
        /// Bind a realm to a zone, or unbind it when no zone ID is given. A realm has at
        ///most one zone and defaults to none.
        /// 
        /// PUT call to `/api/customers/{customerId}/realms/{realmId}/zone` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer.</param>
        /// <param name="realmId">ID of the realm to bind.</param>
        /// <param name="gsReq">The <see cref="SetRealmZoneRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyMessage"/></returns>
        public virtual Promise<EmptyMessage> PutRealmsZone(string customerId, string realmId, SetRealmZoneRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/customers/{customerId}/realms/{realmId}/zone";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            gsUrl = gsUrl.Replace("{realmId}", _requester.EscapeURL(realmId.ToString()));
            // make the request and return the result
            return _requester.Request<EmptyMessage>(Method.PUT, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, this.Serialize<EmptyMessage>);
        }
        /// <summary>
        /// Promote the current Beamo manifest from a source zone into the destination zone.
        ///Zones promote microservices only (no content).
        /// 
        /// POST call to `/api/customers/{customerId}/zones/{zoneId}/promotion` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer.</param>
        /// <param name="zoneId">ID of the zone to promote into.</param>
        /// <param name="gsReq">The <see cref="PromoteZoneRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="PromoteZoneResponse"/></returns>
        public virtual Promise<PromoteZoneResponse> PostZonesPromotion(string customerId, string zoneId, PromoteZoneRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/customers/{customerId}/zones/{zoneId}/promotion";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            gsUrl = gsUrl.Replace("{zoneId}", _requester.EscapeURL(zoneId.ToString()));
            // make the request and return the result
            return _requester.Request<PromoteZoneResponse>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, this.Serialize<PromoteZoneResponse>);
        }
        /// <summary>
        /// Preview what a zone→zone promotion would change, without applying it.
        /// 
        /// GET call to `/api/customers/{customerId}/zones/{zoneId}/promotion` endpoint.
        /// </summary>
        /// <param name="customerId">ID of the customer.</param>
        /// <param name="sourceZoneId">ID of the source zone.</param>
        /// <param name="zoneId">ID of the destination zone.</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="PromoteZoneResponse"/></returns>
        public virtual Promise<PromoteZoneResponse> GetZonesPromotion(string customerId, string zoneId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> sourceZoneId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/customers/{customerId}/zones/{zoneId}/promotion";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            gsUrl = gsUrl.Replace("{zoneId}", _requester.EscapeURL(zoneId.ToString()));
            string gsQuery = "?";
            System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
            if (((sourceZoneId != default(OptionalString)) 
                        && sourceZoneId.HasValue))
            {
                gsQueries.Add(string.Concat("sourceZoneId=", sourceZoneId.Value.ToString()));
            }
            if ((gsQueries.Count > 0))
            {
                gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
                gsUrl = string.Concat(gsUrl, gsQuery);
            }
            // make the request and return the result
            return _requester.Request<PromoteZoneResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<PromoteZoneResponse>);
        }
    }
}
