// this file was copied from nuget package Beamable.Common@7.0.0-PREVIEW.RC17
// https://www.nuget.org/packages/Beamable.Common/7.0.0-PREVIEW.RC17


namespace Beamable.Api.Autogenerated.Push
{
    using Beamable.Api.Autogenerated.Models;
    using Beamable.Common.Content;
    using Beamable.Common;
    using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
    using Method = Beamable.Common.Api.Method;
    using Beamable.Common.Dependencies;
    
    public partial interface IPushApi
    {
        /// <summary>
        /// POST call to `/basic/push/register` endpoint.
        /// </summary>
        /// <param name="gsReq">The <see cref="RegisterReq"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyRsp"/></returns>
        Promise<EmptyRsp> PostRegister(RegisterReq gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// POST call to `/basic/push/send` endpoint.
        /// </summary>
        /// <param name="gsReq">The <see cref="SendReq"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyRsp"/></returns>
        Promise<EmptyRsp> PostSend(SendReq gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
    }
    public partial class PushApi : IPushApi
    {
        /// <summary>
        /// POST call to `/basic/push/register` endpoint.
        /// </summary>
        /// <param name="gsReq">The <see cref="RegisterReq"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyRsp"/></returns>
        public virtual Promise<EmptyRsp> PostRegister(RegisterReq gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/push/register";
            // make the request and return the result
            return _requester.Request<EmptyRsp>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, this.Serialize<EmptyRsp>);
        }
        /// <summary>
        /// POST call to `/basic/push/send` endpoint.
        /// </summary>
        /// <param name="gsReq">The <see cref="SendReq"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyRsp"/></returns>
        public virtual Promise<EmptyRsp> PostSend(SendReq gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/push/send";
            // make the request and return the result
            return _requester.Request<EmptyRsp>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, this.Serialize<EmptyRsp>);
        }
    }
}
