// this file was copied from nuget package Beamable.Common@7.0.0
// https://www.nuget.org/packages/Beamable.Common/7.0.0


namespace Beamable.Api.Autogenerated.Tournaments
{
    using Beamable.Api.Autogenerated.Models;
    using Beamable.Common.Content;
    using Beamable.Common;
    using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
    using Method = Beamable.Common.Api.Method;
    using Beamable.Common.Dependencies;
    
    public partial interface ITournamentsApi
    {
        /// <summary>
        /// POST call to `/basic/tournaments/search/groups` endpoint.
        /// </summary>
        /// <param name="gsReq">The <see cref="GetStatusForGroupsRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetStatusForGroupsResponse"/></returns>
        Promise<GetStatusForGroupsResponse> PostSearchGroups(GetStatusForGroupsRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// GET call to `/basic/tournaments/` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="cycle"></param>
        /// <param name="isRunning"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="TournamentQueryResponse"/></returns>
        Promise<TournamentQueryResponse> Get([System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> cycle, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<bool> isRunning, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// POST call to `/basic/tournaments/` endpoint.
        /// </summary>
        /// <param name="gsReq">The <see cref="JoinRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="PlayerStatus"/></returns>
        Promise<PlayerStatus> Post(JoinRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// GET call to `/basic/tournaments/me/group` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetGroupStatusResponse"/></returns>
        Promise<GetGroupStatusResponse> GetMeGroup([System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// GET call to `/basic/tournaments/rewards` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="RewardsResponse"/></returns>
        Promise<RewardsResponse> GetRewards([System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// POST call to `/basic/tournaments/rewards` endpoint.
        /// </summary>
        /// <param name="gsReq">The <see cref="RewardsRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="RewardsResponse"/></returns>
        Promise<RewardsResponse> PostRewards(RewardsRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// GET call to `/basic/tournaments/global` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="cycle"></param>
        /// <param name="focus"></param>
        /// <param name="from"></param>
        /// <param name="max"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetStandingsResponse"/></returns>
        Promise<GetStandingsResponse> GetGlobal(string tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> cycle, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<long> focus, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> from, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> max, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// GET call to `/basic/tournaments/standings/group` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="cycle"></param>
        /// <param name="focus"></param>
        /// <param name="from"></param>
        /// <param name="max"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetStandingsResponse"/></returns>
        Promise<GetStandingsResponse> GetStandingsGroup(string tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> cycle, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<long> focus, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> from, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> max, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// GET call to `/basic/tournaments/standings` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="cycle"></param>
        /// <param name="focus"></param>
        /// <param name="from"></param>
        /// <param name="max"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetStandingsResponse"/></returns>
        Promise<GetStandingsResponse> GetStandings(string tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> cycle, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<long> focus, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> from, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> max, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// GET call to `/basic/tournaments/admin/player` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="hasUnclaimedRewards"></param>
        /// <param name="playerId"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="AdminGetPlayerStatusResponse"/></returns>
        Promise<AdminGetPlayerStatusResponse> GetAdminPlayer(long playerId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<bool> hasUnclaimedRewards, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// PUT call to `/basic/tournaments/admin/player` endpoint.
        /// </summary>
        /// <param name="gsReq">The <see cref="UpdatePlayerStatusRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="AdminPlayerStatus"/></returns>
        Promise<AdminPlayerStatus> PutAdminPlayer(UpdatePlayerStatusRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// GET call to `/basic/tournaments/me` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="hasUnclaimedRewards"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetPlayerStatusResponse"/></returns>
        Promise<GetPlayerStatusResponse> GetMe([System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<bool> hasUnclaimedRewards, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// GET call to `/basic/tournaments/champions` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="cycles"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetChampionsResponse"/></returns>
        Promise<GetChampionsResponse> GetChampions(int cycles, string tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// POST call to `/basic/tournaments/score` endpoint.
        /// </summary>
        /// <param name="gsReq">The <see cref="ScoreRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyResponse"/></returns>
        Promise<EmptyResponse> PostScore(ScoreRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// GET call to `/basic/tournaments/groups` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="cycle"></param>
        /// <param name="focus"></param>
        /// <param name="from"></param>
        /// <param name="max"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetGroupsResponse"/></returns>
        Promise<GetGroupsResponse> GetGroups(string tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> cycle, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<long> focus, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> from, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> max, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
    }
    public partial class TournamentsApi : ITournamentsApi
    {
        /// <summary>
        /// POST call to `/basic/tournaments/search/groups` endpoint.
        /// </summary>
        /// <param name="gsReq">The <see cref="GetStatusForGroupsRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetStatusForGroupsResponse"/></returns>
        public virtual Promise<GetStatusForGroupsResponse> PostSearchGroups(GetStatusForGroupsRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/tournaments/search/groups";
            // make the request and return the result
            return _requester.Request<GetStatusForGroupsResponse>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, this.Serialize<GetStatusForGroupsResponse>);
        }
        /// <summary>
        /// GET call to `/basic/tournaments/` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="cycle"></param>
        /// <param name="isRunning"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="TournamentQueryResponse"/></returns>
        public virtual Promise<TournamentQueryResponse> Get([System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> cycle, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<bool> isRunning, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/tournaments/";
            string gsQuery = "?";
            System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
            if (((isRunning != default(OptionalBool)) 
                        && isRunning.HasValue))
            {
                gsQueries.Add(string.Concat("isRunning=", isRunning.Value.ToString()));
            }
            if (((contentId != default(OptionalString)) 
                        && contentId.HasValue))
            {
                gsQueries.Add(string.Concat("contentId=", contentId.Value.ToString()));
            }
            if (((cycle != default(OptionalInt)) 
                        && cycle.HasValue))
            {
                gsQueries.Add(string.Concat("cycle=", cycle.Value.ToString()));
            }
            if ((gsQueries.Count > 0))
            {
                gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
                gsUrl = string.Concat(gsUrl, gsQuery);
            }
            // make the request and return the result
            return _requester.Request<TournamentQueryResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<TournamentQueryResponse>);
        }
        /// <summary>
        /// POST call to `/basic/tournaments/` endpoint.
        /// </summary>
        /// <param name="gsReq">The <see cref="JoinRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="PlayerStatus"/></returns>
        public virtual Promise<PlayerStatus> Post(JoinRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/tournaments/";
            // make the request and return the result
            return _requester.Request<PlayerStatus>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, this.Serialize<PlayerStatus>);
        }
        /// <summary>
        /// GET call to `/basic/tournaments/me/group` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetGroupStatusResponse"/></returns>
        public virtual Promise<GetGroupStatusResponse> GetMeGroup([System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/tournaments/me/group";
            string gsQuery = "?";
            System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
            if (((contentId != default(OptionalString)) 
                        && contentId.HasValue))
            {
                gsQueries.Add(string.Concat("contentId=", contentId.Value.ToString()));
            }
            if ((gsQueries.Count > 0))
            {
                gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
                gsUrl = string.Concat(gsUrl, gsQuery);
            }
            // make the request and return the result
            return _requester.Request<GetGroupStatusResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<GetGroupStatusResponse>);
        }
        /// <summary>
        /// GET call to `/basic/tournaments/rewards` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="RewardsResponse"/></returns>
        public virtual Promise<RewardsResponse> GetRewards([System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/tournaments/rewards";
            string gsQuery = "?";
            System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
            if (((tournamentId != default(OptionalString)) 
                        && tournamentId.HasValue))
            {
                gsQueries.Add(string.Concat("tournamentId=", tournamentId.Value.ToString()));
            }
            if (((contentId != default(OptionalString)) 
                        && contentId.HasValue))
            {
                gsQueries.Add(string.Concat("contentId=", contentId.Value.ToString()));
            }
            if ((gsQueries.Count > 0))
            {
                gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
                gsUrl = string.Concat(gsUrl, gsQuery);
            }
            // make the request and return the result
            return _requester.Request<RewardsResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<RewardsResponse>);
        }
        /// <summary>
        /// POST call to `/basic/tournaments/rewards` endpoint.
        /// </summary>
        /// <param name="gsReq">The <see cref="RewardsRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="RewardsResponse"/></returns>
        public virtual Promise<RewardsResponse> PostRewards(RewardsRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/tournaments/rewards";
            // make the request and return the result
            return _requester.Request<RewardsResponse>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, this.Serialize<RewardsResponse>);
        }
        /// <summary>
        /// GET call to `/basic/tournaments/global` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="cycle"></param>
        /// <param name="focus"></param>
        /// <param name="from"></param>
        /// <param name="max"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetStandingsResponse"/></returns>
        public virtual Promise<GetStandingsResponse> GetGlobal(string tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> cycle, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<long> focus, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> from, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> max, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/tournaments/global";
            string gsQuery = "?";
            System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
            gsQueries.Add(string.Concat("tournamentId=", _requester.EscapeURL(tournamentId.ToString())));
            if (((max != default(OptionalInt)) 
                        && max.HasValue))
            {
                gsQueries.Add(string.Concat("max=", max.Value.ToString()));
            }
            if (((focus != default(OptionalLong)) 
                        && focus.HasValue))
            {
                gsQueries.Add(string.Concat("focus=", focus.Value.ToString()));
            }
            if (((cycle != default(OptionalInt)) 
                        && cycle.HasValue))
            {
                gsQueries.Add(string.Concat("cycle=", cycle.Value.ToString()));
            }
            if (((from != default(OptionalInt)) 
                        && from.HasValue))
            {
                gsQueries.Add(string.Concat("from=", from.Value.ToString()));
            }
            if (((contentId != default(OptionalString)) 
                        && contentId.HasValue))
            {
                gsQueries.Add(string.Concat("contentId=", contentId.Value.ToString()));
            }
            if ((gsQueries.Count > 0))
            {
                gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
                gsUrl = string.Concat(gsUrl, gsQuery);
            }
            // make the request and return the result
            return _requester.Request<GetStandingsResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<GetStandingsResponse>);
        }
        /// <summary>
        /// GET call to `/basic/tournaments/standings/group` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="cycle"></param>
        /// <param name="focus"></param>
        /// <param name="from"></param>
        /// <param name="max"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetStandingsResponse"/></returns>
        public virtual Promise<GetStandingsResponse> GetStandingsGroup(string tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> cycle, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<long> focus, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> from, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> max, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/tournaments/standings/group";
            string gsQuery = "?";
            System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
            gsQueries.Add(string.Concat("tournamentId=", _requester.EscapeURL(tournamentId.ToString())));
            if (((max != default(OptionalInt)) 
                        && max.HasValue))
            {
                gsQueries.Add(string.Concat("max=", max.Value.ToString()));
            }
            if (((focus != default(OptionalLong)) 
                        && focus.HasValue))
            {
                gsQueries.Add(string.Concat("focus=", focus.Value.ToString()));
            }
            if (((cycle != default(OptionalInt)) 
                        && cycle.HasValue))
            {
                gsQueries.Add(string.Concat("cycle=", cycle.Value.ToString()));
            }
            if (((from != default(OptionalInt)) 
                        && from.HasValue))
            {
                gsQueries.Add(string.Concat("from=", from.Value.ToString()));
            }
            if (((contentId != default(OptionalString)) 
                        && contentId.HasValue))
            {
                gsQueries.Add(string.Concat("contentId=", contentId.Value.ToString()));
            }
            if ((gsQueries.Count > 0))
            {
                gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
                gsUrl = string.Concat(gsUrl, gsQuery);
            }
            // make the request and return the result
            return _requester.Request<GetStandingsResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<GetStandingsResponse>);
        }
        /// <summary>
        /// GET call to `/basic/tournaments/standings` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="cycle"></param>
        /// <param name="focus"></param>
        /// <param name="from"></param>
        /// <param name="max"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetStandingsResponse"/></returns>
        public virtual Promise<GetStandingsResponse> GetStandings(string tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> cycle, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<long> focus, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> from, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> max, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/tournaments/standings";
            string gsQuery = "?";
            System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
            gsQueries.Add(string.Concat("tournamentId=", _requester.EscapeURL(tournamentId.ToString())));
            if (((max != default(OptionalInt)) 
                        && max.HasValue))
            {
                gsQueries.Add(string.Concat("max=", max.Value.ToString()));
            }
            if (((focus != default(OptionalLong)) 
                        && focus.HasValue))
            {
                gsQueries.Add(string.Concat("focus=", focus.Value.ToString()));
            }
            if (((cycle != default(OptionalInt)) 
                        && cycle.HasValue))
            {
                gsQueries.Add(string.Concat("cycle=", cycle.Value.ToString()));
            }
            if (((from != default(OptionalInt)) 
                        && from.HasValue))
            {
                gsQueries.Add(string.Concat("from=", from.Value.ToString()));
            }
            if (((contentId != default(OptionalString)) 
                        && contentId.HasValue))
            {
                gsQueries.Add(string.Concat("contentId=", contentId.Value.ToString()));
            }
            if ((gsQueries.Count > 0))
            {
                gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
                gsUrl = string.Concat(gsUrl, gsQuery);
            }
            // make the request and return the result
            return _requester.Request<GetStandingsResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<GetStandingsResponse>);
        }
        /// <summary>
        /// GET call to `/basic/tournaments/admin/player` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="hasUnclaimedRewards"></param>
        /// <param name="playerId"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="AdminGetPlayerStatusResponse"/></returns>
        public virtual Promise<AdminGetPlayerStatusResponse> GetAdminPlayer(long playerId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<bool> hasUnclaimedRewards, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/tournaments/admin/player";
            string gsQuery = "?";
            System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
            gsQueries.Add(string.Concat("playerId=", _requester.EscapeURL(playerId.ToString())));
            if (((tournamentId != default(OptionalString)) 
                        && tournamentId.HasValue))
            {
                gsQueries.Add(string.Concat("tournamentId=", tournamentId.Value.ToString()));
            }
            if (((contentId != default(OptionalString)) 
                        && contentId.HasValue))
            {
                gsQueries.Add(string.Concat("contentId=", contentId.Value.ToString()));
            }
            if (((hasUnclaimedRewards != default(OptionalBool)) 
                        && hasUnclaimedRewards.HasValue))
            {
                gsQueries.Add(string.Concat("hasUnclaimedRewards=", hasUnclaimedRewards.Value.ToString()));
            }
            if ((gsQueries.Count > 0))
            {
                gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
                gsUrl = string.Concat(gsUrl, gsQuery);
            }
            // make the request and return the result
            return _requester.Request<AdminGetPlayerStatusResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<AdminGetPlayerStatusResponse>);
        }
        /// <summary>
        /// PUT call to `/basic/tournaments/admin/player` endpoint.
        /// </summary>
        /// <param name="gsReq">The <see cref="UpdatePlayerStatusRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="AdminPlayerStatus"/></returns>
        public virtual Promise<AdminPlayerStatus> PutAdminPlayer(UpdatePlayerStatusRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/tournaments/admin/player";
            // make the request and return the result
            return _requester.Request<AdminPlayerStatus>(Method.PUT, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, this.Serialize<AdminPlayerStatus>);
        }
        /// <summary>
        /// GET call to `/basic/tournaments/me` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="hasUnclaimedRewards"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetPlayerStatusResponse"/></returns>
        public virtual Promise<GetPlayerStatusResponse> GetMe([System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<bool> hasUnclaimedRewards, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/tournaments/me";
            string gsQuery = "?";
            System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
            if (((tournamentId != default(OptionalString)) 
                        && tournamentId.HasValue))
            {
                gsQueries.Add(string.Concat("tournamentId=", tournamentId.Value.ToString()));
            }
            if (((contentId != default(OptionalString)) 
                        && contentId.HasValue))
            {
                gsQueries.Add(string.Concat("contentId=", contentId.Value.ToString()));
            }
            if (((hasUnclaimedRewards != default(OptionalBool)) 
                        && hasUnclaimedRewards.HasValue))
            {
                gsQueries.Add(string.Concat("hasUnclaimedRewards=", hasUnclaimedRewards.Value.ToString()));
            }
            if ((gsQueries.Count > 0))
            {
                gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
                gsUrl = string.Concat(gsUrl, gsQuery);
            }
            // make the request and return the result
            return _requester.Request<GetPlayerStatusResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<GetPlayerStatusResponse>);
        }
        /// <summary>
        /// GET call to `/basic/tournaments/champions` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="cycles"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetChampionsResponse"/></returns>
        public virtual Promise<GetChampionsResponse> GetChampions(int cycles, string tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/tournaments/champions";
            string gsQuery = "?";
            System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
            gsQueries.Add(string.Concat("tournamentId=", _requester.EscapeURL(tournamentId.ToString())));
            gsQueries.Add(string.Concat("cycles=", _requester.EscapeURL(cycles.ToString())));
            if (((contentId != default(OptionalString)) 
                        && contentId.HasValue))
            {
                gsQueries.Add(string.Concat("contentId=", contentId.Value.ToString()));
            }
            if ((gsQueries.Count > 0))
            {
                gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
                gsUrl = string.Concat(gsUrl, gsQuery);
            }
            // make the request and return the result
            return _requester.Request<GetChampionsResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<GetChampionsResponse>);
        }
        /// <summary>
        /// POST call to `/basic/tournaments/score` endpoint.
        /// </summary>
        /// <param name="gsReq">The <see cref="ScoreRequest"/> instance to use for the request</param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="EmptyResponse"/></returns>
        public virtual Promise<EmptyResponse> PostScore(ScoreRequest gsReq, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/tournaments/score";
            // make the request and return the result
            return _requester.Request<EmptyResponse>(Method.POST, gsUrl, Beamable.Serialization.JsonSerializable.ToJson(gsReq), includeAuthHeader, this.Serialize<EmptyResponse>);
        }
        /// <summary>
        /// GET call to `/basic/tournaments/groups` endpoint.
        /// </summary>
        /// <param name="contentId"></param>
        /// <param name="cycle"></param>
        /// <param name="focus"></param>
        /// <param name="from"></param>
        /// <param name="max"></param>
        /// <param name="tournamentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="GetGroupsResponse"/></returns>
        public virtual Promise<GetGroupsResponse> GetGroups(string tournamentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> contentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> cycle, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<long> focus, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> from, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<int> max, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/basic/tournaments/groups";
            string gsQuery = "?";
            System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
            gsQueries.Add(string.Concat("tournamentId=", _requester.EscapeURL(tournamentId.ToString())));
            if (((max != default(OptionalInt)) 
                        && max.HasValue))
            {
                gsQueries.Add(string.Concat("max=", max.Value.ToString()));
            }
            if (((focus != default(OptionalLong)) 
                        && focus.HasValue))
            {
                gsQueries.Add(string.Concat("focus=", focus.Value.ToString()));
            }
            if (((cycle != default(OptionalInt)) 
                        && cycle.HasValue))
            {
                gsQueries.Add(string.Concat("cycle=", cycle.Value.ToString()));
            }
            if (((from != default(OptionalInt)) 
                        && from.HasValue))
            {
                gsQueries.Add(string.Concat("from=", from.Value.ToString()));
            }
            if (((contentId != default(OptionalString)) 
                        && contentId.HasValue))
            {
                gsQueries.Add(string.Concat("contentId=", contentId.Value.ToString()));
            }
            if ((gsQueries.Count > 0))
            {
                gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
                gsUrl = string.Concat(gsUrl, gsQuery);
            }
            // make the request and return the result
            return _requester.Request<GetGroupsResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<GetGroupsResponse>);
        }
    }
}
