#pragma once

#include "CoreMinimal.h"
#include "BeamPlatformNotificationsSubsystem.h"
#include "Kismet/BlueprintFunctionLibrary.h"

#include "BeamCampaignIntentData.generated.h"

/**
 * The campaign "notification intent data" a Beamable campaign attaches to a push, lifted out of the
 * raw notification payload.
 *
 * This lives in the plugin rather than in a game because it is a cross-engine wire contract --- Unity
 * ships the same thing as NotificationIntentData in Payloads.cs, React Native as parsing.ts --- and
 * because reconciling the platform differences below is exactly the kind of normalisation
 * UBeamPlatformNotificationsSubsystem::ParseNotification already does for the deep link.
 *
 * IMPORTANT for maintainers: this folder is regenerated by install-beamplatformnotifications.sh,
 * which rm -rf's the plugin directory. These two files must be mirrored in
 * BeamableProduct/beam-native-mobile/Unreal/Source/BeamPlatformNotifications/ or the next install
 * deletes them.
 */

/** One offer carried by a campaign push. Wire shape: {itemId, value, customData}. */
USTRUCT(BlueprintType)
struct BEAMPLATFORMNOTIFICATIONS_API FBeamCampaignPushOffer
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	FString ItemId;

	/**
	 * `value` is typed "string | number" on the wire. Both forms are kept, plus which one arrived,
	 * so the funnel event can re-emit a number as a number rather than quoting it.
	 */
	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	FString ValueAsString;

	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	double ValueAsNumber = 0.0;

	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	bool bValueIsNumber = false;

	/** Free-form and possibly nested, so it is carried as raw JSON and passed through verbatim. */
	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	FString CustomDataJson;
};

/**
 * Everything a campaign push carries beyond its title and body.
 *
 * The payload reaches Unreal through FBMNNotificationData::RawJson, whose shape differs by platform:
 *   * iOS   --- the Swift Codable already lifts the campaign fields to the top level, `offers` and
 *               `campaignData` arrive as real JSON, and outreach is spelled "outreachId".
 *   * Android --- everything is a flat string->string map, `offers` is a JSON *string*, and outreach
 *               is spelled "beam_outreach".
 * ParseFromRawJson accepts both, plus the userInfo / dataPayload nesting.
 */
USTRUCT(BlueprintType)
struct BEAMPLATFORMNOTIFICATIONS_API FBeamCampaignIntentData
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	FString CampaignId;

	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	FString NodeId;

	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	FString GamerTag;

	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	FString AccountId;

	/** "<cid>.<pid>". The native funnel drops the event unless this contains a dot. */
	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	FString CidPid;

	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	FString Deeplink;

	/** Per-recipient join key. Accepted as either "outreachId" or "beam_outreach". */
	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	FString OutreachId;

	/** "campaign:{id}:{version}:{node}". */
	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	FString TrackId;

	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	TArray<FBeamCampaignPushOffer> Offers;

	/** Operator-authored free-form object, kept raw. */
	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	FString CampaignDataJson;

	/** The grant this notification points at --- the deep-link target for an offer screen. */
	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	FString OfferGrantId;

	/** Every grant the push carried, when it templated in more than one. */
	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	TArray<FString> OfferGrantIds;

	/**
	 * Every remaining key from the payload, coerced to string: imageUrl, style, category, badge,
	 * title/body when the platform kept them here, and any authored passthrough.
	 */
	UPROPERTY(BlueprintReadOnly, Category="Notifications|Campaign")
	TMap<FString, FString> Extras;

	/**
	 * Whether this notification belongs to a tracked campaign. Both natives require campaignId AND
	 * nodeId before they will emit anything, so a false here means the funnel will stay silent --- and
	 * that is correct: fabricating campaign coordinates would corrupt the funnel.
	 *
	 * Blueprint reaches this through UBeamCampaignIntentLibrary::IsTrackedCampaign --- a USTRUCT
	 * cannot carry a UFUNCTION.
	 */
	bool IsTrackedCampaign() const { return !CampaignId.IsEmpty() && !NodeId.IsEmpty(); }

	/**
	 * Whether the identity fields the native funnel POST needs are present. The native layer checks
	 * exactly this (a cidPid containing a dot, and a non-empty gamerTag) and drops the event without
	 * logging, so callers should test this and warn rather than wonder why the Portal shows zeros.
	 */
	bool HasFunnelCredentials() const { return CidPid.Contains(TEXT(".")) && !GamerTag.IsEmpty(); }
};

UCLASS()
class BEAMPLATFORMNOTIFICATIONS_API UBeamCampaignIntentLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	/** \copybrief FBeamCampaignIntentData::IsTrackedCampaign */
	UFUNCTION(BlueprintPure, Category="Notifications|Campaign")
	static bool IsTrackedCampaign(const FBeamCampaignIntentData& Intent) { return Intent.IsTrackedCampaign(); }

	/** \copybrief FBeamCampaignIntentData::HasFunnelCredentials */
	UFUNCTION(BlueprintPure, Category="Notifications|Campaign")
	static bool HasFunnelCredentials(const FBeamCampaignIntentData& Intent) { return Intent.HasFunnelCredentials(); }

	/** Lifts the campaign intent data out of a notification delivered by the subsystem. */
	UFUNCTION(BlueprintPure, Category="Notifications|Campaign")
	static FBeamCampaignIntentData ParseFromNotification(const FBMNNotificationData& Notification);

	/** As ParseFromNotification, but straight from a payload string. Handy for tests and tooling. */
	UFUNCTION(BlueprintPure, Category="Notifications|Campaign")
	static FBeamCampaignIntentData ParseFromRawJson(const FString& RawJson);

	/**
	 * Builds the OfferTrackRequest JSON that TrackOfferClicked / TrackOfferConverted expect. Pass an
	 * offer with an empty ItemId to omit the `offer` member entirely, which both natives accept.
	 */
	UFUNCTION(BlueprintPure, Category="Notifications|Campaign")
	static FString BuildOfferTrackRequestJson(const FBeamCampaignIntentData& Intent, const FBeamCampaignPushOffer& Offer);

	/**
	 * Builds the AuthConfig JSON that ConfigureAuth expects.
	 * @param ExpiresAtEpochMs Expiry in epoch MILLISECONDS. Mind the units: FBeamAuthToken::IssuedAt is
	 *        in seconds while ExpiresIn is in milliseconds, and getting this wrong yields an
	 *        already-expired token whose funnel authenticates once and then goes quiet.
	 */
	UFUNCTION(BlueprintPure, Category="Notifications|Campaign")
	static FString BuildAuthConfigJson(const FString& AccessToken, const FString& RefreshToken, int64 ExpiresAtEpochMs, const FString& Cid, const FString& Pid, const FString& Host);
};
