using Beamable.Api.Autogenerated.Models;
using Beamable.Common.Api;
using Beamable.Common.BeamCli;
using Beamable.Common.BeamCli.Contracts;
using Beamable.Server;
using cli.Utils;
using Newtonsoft.Json;
using SharpYaml.Serialization;
using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
using System.Threading.Channels;
using JsonElement = System.Text.Json.JsonElement;
using JsonSerializer = System.Text.Json.JsonSerializer;

namespace cli.Content;

public partial class ContentService
{
	/// <summary>
	/// Gets the absolute path to the root directory for all content history data.
	/// This is the base directory under which entries, changelists, and content subdirectories are stored.
	/// </summary>
	private string ContentHistoryRootPath => _config.GetConfigPath(ConfigService.CONTENT_HISTORY_LOCAL_DIR);

	/// <summary>
	/// Gets the absolute path to the directory where content history entry files are stored.
	/// Entry files contain metadata about each published manifest (UID, timestamp, publisher, affected content IDs).
	/// Structure: {ContentHistoryEntriesPath}/{pid}/{manifestId}/{timestamp}¬{uid}.json
	/// </summary>
	private string ContentHistoryEntriesPath => _config.GetConfigPath(ConfigService.CONTENT_HISTORY_LOCAL_ENTRIES_DIR);

	/// <summary>
	/// Gets the absolute path to the directory where content history changelist files are stored.
	/// Changelist files contain the full diff between two manifests (created, modified, removed content).
	/// Structure: {ContentHistoryChangelistsPath}/{pid}/{manifestId}/{uid}.json
	/// </summary>
	private string ContentHistoryChangelistsPath => _config.GetConfigPath(ConfigService.CONTENT_HISTORY_LOCAL_CHANGELISTS_DIR);

	/// <summary>
	/// Gets the absolute path to the directory where content history content files are stored.
	/// Content files contain the actual content data at specific points in history.
	/// Structure: {ContentHistoryContentPath}/{pid}/{manifestId}/{uid}/{contentId}.json
	/// </summary>
	private string ContentHistoryContentPath => _config.GetConfigPath(ConfigService.CONTENT_HISTORY_LOCAL_CONTENT_DIR);

	/// <summary>
	/// Dictionary of FileSystemWatchers for monitoring content history entry files, keyed by (pid, manifest) tuple.
	/// Each watcher monitors Created, Deleted, Changed, and Renamed events for JSON files in the entries directory.
	/// Only one watcher is maintained per (pid, manifest) combination; adding a new watcher overwrites any existing one.
	/// </summary>
	private Dictionary<(string pid, string manifest), FileSystemWatcher> _contentHistoryEntryWatchers = new();

	/// <summary>
	/// Unbounded channel for communicating content history entry file change events from FileSystemWatchers to async consumers.
	/// Receives ChangedContentHistoryEntryFile messages containing file paths, timestamps, and manifest UIDs.
	/// Used by ListenToContentHistoryEntries to batch and stream file change notifications.
	/// </summary>
	private readonly Channel<ChangedContentHistoryEntryFile> _channelContentHistoryEntries;

	/// <summary>
	/// Dictionary of FileSystemWatchers for monitoring content history changelist files, keyed by (pid, manifest) tuple.
	/// Each watcher monitors Created, Deleted, Changed, and Renamed events for JSON files in the changelists directory.
	/// Distinguishes between read access (LastAccessTime) and write modifications (LastWriteTime) for Changed events.
	/// Only one watcher is maintained per (pid, manifest) combination; adding a new watcher overwrites any existing one.
	/// </summary>
	private Dictionary<(string pid, string manifest), FileSystemWatcher> _contentHistoryChangelistWatchers = new();

	/// <summary>
	/// Unbounded channel for communicating content history changelist file change events from FileSystemWatchers to async consumers.
	/// Receives ChangedContentHistoryChangelistFile messages containing file paths, manifest UIDs, and read/write access flags.
	/// Used by ListenToContentHistoryChangelists to batch and stream file change notifications.
	/// </summary>
	private readonly Channel<ChangedContentHistoryChangelistFile> _channelContentHistoryChangelists;

	/// <summary>
	/// Semaphore (max count: 1) to serialize access to content history entry files and prevent race conditions.
	/// Protects concurrent reads/writes between FileSystemWatchers, sync operations, and file I/O in the entries directory.
	/// Must be acquired before any file system operations on entry files to ensure data consistency.
	/// </summary>
	private readonly System.Threading.SemaphoreSlim _contentHistoryEntriesFileSystemSemaphore = new(1, 1);

	/// <summary>
	/// Semaphore (max count: 1) to serialize access to content history changelist files and prevent race conditions.
	/// Protects concurrent reads/writes between FileSystemWatchers, sync operations, and file I/O in the changelists directory.
	/// Must be acquired before any file system operations on changelist files to ensure data consistency.
	/// </summary>
	private readonly System.Threading.SemaphoreSlim _contentHistoryChangelistsFileSystemSemaphore = new(1, 1);

	/// <summary>
	/// Semaphore (max count: 1) to serialize access to content history content files and prevent race conditions.
	/// Protects concurrent reads/writes between FileSystemWatchers, sync operations, and file I/O in the content directory.
	/// Must be acquired before any file system operations on content files to ensure data consistency.
	/// </summary>
	private readonly System.Threading.SemaphoreSlim _contentHistoryContentFileSystemSemaphore = new(1, 1);


	/// <summary>
	/// Ensures the content history entries folder exists for the specified PID and manifest.
	/// Creates the directory structure at {ContentHistoryEntriesPath}/{pid}/{manifest} if it doesn't exist.
	/// </summary>
	/// <param name="created">Output parameter indicating whether the directory was created (true) or already existed (false)</param>
	/// <param name="pid">The realm id (PID) for which to ensure the entries folder exists</param>
	/// <param name="manifest">The manifest ID, defaults to "global" if not specified</param>
	/// <returns>The absolute path to the content history entries folder</returns>
	public string EnsureContentHistoryEntriesFolderExists(out bool created, string pid, string manifest = "global")
	{
		created = false;

		var path = Path.Combine(ContentHistoryEntriesPath, pid, manifest);
		if (!Directory.Exists(path))
		{
			Directory.CreateDirectory(path);
			created = true;
		}

		return path;
	}

	/// <summary>
	/// Ensures the content history changelists folder exists for the specified PID and manifest.
	/// Creates the directory structure at {ContentHistoryChangelistsPath}/{pid}/{manifest} if it doesn't exist.
	/// </summary>
	/// <param name="created">Output parameter indicating whether the directory was created (true) or already existed (false)</param>
	/// <param name="pid">The realm id (PID) for which to ensure the changelists folder exists</param>
	/// <param name="manifest">The manifest ID, defaults to "global" if not specified</param>
	/// <returns>The absolute path to the content history changelists folder</returns>
	public string EnsureContentHistoryChangelistsFolderExists(out bool created, string pid, string manifest = "global")
	{
		created = false;

		var path = Path.Combine(ContentHistoryChangelistsPath, pid, manifest);
		if (!Directory.Exists(path))
		{
			Directory.CreateDirectory(path);
			created = true;
		}

		return path;
	}

	/// <summary>
	/// Ensures the content history content folder exists for the specified PID and manifest.
	/// Creates the directory structure at {ContentHistoryContentPath}/{pid}/{manifest} if it doesn't exist.
	/// Individual manifest UIDs are stored as subfolders under this path.
	/// </summary>
	/// <param name="created">Output parameter indicating whether the directory was created (true) or already existed (false)</param>
	/// <param name="pid">The realm id (PID) for which to ensure the content folder exists</param>
	/// <param name="manifest">The manifest ID, defaults to "global" if not specified</param>
	/// <returns>The absolute path to the content history content folder</returns>
	public string EnsureContentHistoryContentFolderExists(out bool created, string pid, string manifest = "global")
	{
		created = false;

		// Listen at the PID level under the Content root. Individual manifest UIDs are subfolders under this path.
		var path = Path.Combine(ContentHistoryContentPath, pid, manifest);
		if (!Directory.Exists(path))
		{
			Directory.CreateDirectory(path);
			created = true;
		}

		return path;
	}


	/// <summary>
	/// Monitors filesystem changes to content history entry files and streams change events asynchronously.
	/// Creates a FileSystemWatcher to track Created, Deleted, Changed, and Renamed events for JSON files in the entries directory.
	/// Changes are batched together (100ms window) to handle multiple simultaneous file modifications.
	/// </summary>
	/// <param name="pid">The realm id (PID) whose content history entries to monitor</param>
	/// <param name="manifestId">The manifest ID to monitor, defaults to "global"</param>
	/// <param name="token">Cancellation token to stop monitoring</param>
	/// <returns>
	/// An async enumerable of LocalContentHistoryEntryFileChanges, each containing a batch of file change events.
	/// Yields batches of changes as they occur with a 100ms debounce window.
	/// </returns>
	/// <remarks>
	/// Edge cases:
	/// - Uses event disambiguation based on LastWrite timestamps to prevent duplicate events (Windows fires both Created and Changed for new files)
	/// - Only one watcher per (pid, manifestId) tuple is stored in the dictionary (overwrites if called multiple times)
	/// - Breaks and yields when cancellation is requested
	/// - All file paths must end with .json extension
	/// - Renamed events include both old and new file information
	/// </remarks>
	public async IAsyncEnumerable<LocalContentHistoryEntryFileChanges> ListenToContentHistoryEntries(string pid, string manifestId = "global", [EnumeratorCancellation] CancellationToken token = default)
	{
		// Make sure the folder we're supposed to be watching exists.
		var contentFolder = EnsureContentHistoryEntriesFolderExists(out _, _requester.Pid, manifestId);

		// Create the file watcher
		_contentHistoryEntryWatchers.Add((pid, manifestId), new FileSystemWatcher());

		// We need to keep track of the "LastWrite" time for each content entry to disambiguate multiple events firing simultaneously for the same file.
		// For example, on Windows, a Created event is always fired alongside a Changed event of the same file (because of "reasons", I guess)
		// This dictionary helps us fire off only one relevant event at a time even when the file watcher gets confused about the desirable semantics.
		var eventDisambiguationHelper = new Dictionary<string, long>();

		// Set up the file watcher...
		var watcher = _contentHistoryEntryWatchers[(pid, manifestId)];
		watcher.BeginInit();
		watcher.Path = contentFolder;
		watcher.IncludeSubdirectories = true;
		watcher.Filter = "*.json";
		watcher.EnableRaisingEvents = true;
		watcher.NotifyFilter = (NotifyFilters.Attributes |
		                        NotifyFilters.CreationTime |
		                        NotifyFilters.DirectoryName |
		                        NotifyFilters.FileName |
		                        NotifyFilters.LastWrite);
		watcher.Error += (_, e) => Log.Error(e.GetException().ToString());
		watcher.Disposed += (_, e) => Log.Error($"Disposed {e}");
		watcher.Created += (_, e) => { OnFilesChanged(e); };
		watcher.Deleted += (_, e) => { OnFilesChanged(e); };
		watcher.Renamed += (_, e) => { OnFilesChanged(e); };
		watcher.Changed += (_, e) => { OnFilesChanged(e); };
		watcher.EndInit();

		// Keep waiting for messages from the set up file watcher.
		var reader = _channelContentHistoryEntries.Reader;

		while (true)
		{
			// If the operation was canceled, we break out.
			if (token.IsCancellationRequested)
			{
				break;
			}

			try
			{
				await reader.WaitToReadAsync(token);

				// For the case which multiple files are edited at the same time, the watcher triggers one message for each one.
				// So to batch it together, we wait 100 ms and then try to read from the buffer.
				await Task.Delay(100, token);
			}
			catch (OperationCanceledException)
			{
				Log.Debug($"{nameof(ListenToLocalContentFileChanges)} was cancelled");
				break;
			}

			// Get all the files that were changed respecting the PID filter.
			var batchedChanges = new LocalContentHistoryEntryFileChanges() { AllFileChanges = new() };
			while (reader.TryRead(out var changed))
			{
				batchedChanges.AllFileChanges.Add(changed);
			}


			yield return batchedChanges;
		}

		yield break;

		void OnFilesChanged(FileSystemEventArgs e)
		{
			var lastWriteTime = new DateTimeOffset(File.GetLastWriteTime(e.FullPath)).ToUnixTimeMilliseconds();
			if (e.ChangeType == WatcherChangeTypes.Created)
			{
				var changedEntry = new ChangedContentHistoryEntryFile { OwnerPid = pid };
				changedEntry.OwnerPid = pid;
				changedEntry.OwnerManifestId = manifestId;

				ChangedContentHistoryEntryFile.TryParseEntryFileName(Path.GetFileNameWithoutExtension(e.Name), out var timestamp, out var uid);
				changedEntry.UnixTimestamp = timestamp;
				changedEntry.ManifestUid = uid;
				changedEntry.FullFilePath = e.FullPath;
				changedEntry.OldUnixTimestamp = 0L;
				changedEntry.OldManifestUid = "";
				changedEntry.OldFullFilePath = "";

				if (!eventDisambiguationHelper.TryGetValue(e.FullPath, out var time) || time != lastWriteTime)
				{
					eventDisambiguationHelper[e.FullPath] = lastWriteTime;
					Log.Verbose($"Created file ({lastWriteTime}): {JsonConvert.SerializeObject(changedEntry)} ");
					_channelContentHistoryEntries.Writer.TryWrite(changedEntry);
				}
			}
			else if (e.ChangeType == WatcherChangeTypes.Deleted)
			{
				var changedContent = new ChangedContentHistoryEntryFile { OwnerPid = pid };
				changedContent.OwnerPid = pid;
				changedContent.OwnerManifestId = manifestId;

				ChangedContentHistoryEntryFile.TryParseEntryFileName(Path.GetFileNameWithoutExtension(e.Name), out var timestamp, out var uid);
				changedContent.UnixTimestamp = changedContent.OldUnixTimestamp = timestamp;
				changedContent.ManifestUid = changedContent.OldManifestUid = uid;
				changedContent.FullFilePath = "";
				changedContent.OldFullFilePath = e.FullPath;
				Log.Verbose($"Deleted file: {JsonConvert.SerializeObject(changedContent)} ");
				_channelContentHistoryEntries.Writer.TryWrite(changedContent);
			}
			else if (e.ChangeType == WatcherChangeTypes.Changed)
			{
				var changedContent = new ChangedContentHistoryEntryFile { OwnerPid = pid };
				changedContent.OwnerPid = pid;
				changedContent.OwnerManifestId = manifestId;

				ChangedContentHistoryEntryFile.TryParseEntryFileName(Path.GetFileNameWithoutExtension(e.Name), out var timestamp, out var uid);
				changedContent.UnixTimestamp = changedContent.OldUnixTimestamp = timestamp;
				changedContent.ManifestUid = changedContent.OldManifestUid = uid;
				changedContent.FullFilePath = changedContent.OldFullFilePath = e.FullPath;

				if (!eventDisambiguationHelper.TryGetValue(e.FullPath, out var time) || time != lastWriteTime)
				{
					eventDisambiguationHelper[e.FullPath] = lastWriteTime;
					Log.Verbose($"Changed file ({lastWriteTime}): {JsonConvert.SerializeObject(changedContent)} ");
					_channelContentHistoryEntries.Writer.TryWrite(changedContent);
				}
			}
			else if (e.ChangeType == WatcherChangeTypes.Renamed)
			{
				if (e is RenamedEventArgs renamedEventArgs)
				{
					var renamedContent = new ChangedContentHistoryEntryFile();
					renamedContent.OwnerPid = pid;
					renamedContent.OwnerManifestId = manifestId;

					ChangedContentHistoryEntryFile.TryParseEntryFileName(Path.GetFileNameWithoutExtension(renamedEventArgs.Name), out var newTimestamp, out var newUid);
					renamedContent.UnixTimestamp = newTimestamp;
					renamedContent.ManifestUid = newUid;
					renamedContent.FullFilePath = renamedEventArgs.FullPath;

					ChangedContentHistoryEntryFile.TryParseEntryFileName(Path.GetFileNameWithoutExtension(renamedEventArgs.OldName), out var oldTimestamp, out var oldUid);
					renamedContent.OldUnixTimestamp = oldTimestamp;
					renamedContent.OldManifestUid = oldUid;
					renamedContent.OldFullFilePath = renamedEventArgs.OldFullPath;
					Log.Verbose($"Renamed file: {JsonConvert.SerializeObject(renamedContent)} ");

					_channelContentHistoryEntries.Writer.TryWrite(renamedContent);
				}
			}
		}
	}

	/// <summary>
	/// Monitors filesystem changes to content history changelist files and streams change events asynchronously.
	/// Creates a FileSystemWatcher to track Created, Deleted, Changed, and Renamed events for JSON files in the changelists directory.
	/// Distinguishes between read-only access (LastAccessTime change) and modification (LastWriteTime change) for Changed events.
	/// Changes are batched together (100ms window) to handle multiple simultaneous file modifications.
	/// </summary>
	/// <param name="pid">The realm id (PID) whose content history changelists to monitor</param>
	/// <param name="manifestId">The manifest ID to monitor, defaults to "global"</param>
	/// <param name="token">Cancellation token to stop monitoring</param>
	/// <returns>
	/// An async enumerable of LocalContentHistoryChangelistFileChanges, each containing a batch of file change events.
	/// Yields batches of changes as they occur with a 100ms debounce window.
	/// </returns>
	/// <remarks>
	/// Edge cases:
	/// - Tracks both LastAccessTime and LastWriteTime to distinguish reads vs writes on Changed events
	/// - Uses event disambiguation to prevent duplicate events (same file, same timestamp)
	/// - Sets WasReadAccessed=true when only access time changed, false when write time changed
	/// - Only one watcher per (pid, manifestId) tuple is stored in the dictionary
	/// - Breaks and yields when cancellation is requested
	/// - All file paths must end with .json extension
	/// - Renamed events include both old and new file information
	/// </remarks>
	public async IAsyncEnumerable<LocalContentHistoryChangelistFileChanges> ListenToContentHistoryChangelists(string pid, string manifestId = "global", [EnumeratorCancellation] CancellationToken token = default)
	{
		// Make sure the folder we're supposed to be watching exists.
		var changelistsFolder = EnsureContentHistoryChangelistsFolderExists(out _, pid, manifestId);

		// Create the file watcher
		_contentHistoryChangelistWatchers.Add((pid, manifestId), new FileSystemWatcher());

		// Disambiguation helper for simultaneous events
		var eventDisambiguationHelper = new Dictionary<string, long>();

		// Set up the file watcher...
		var watcher = _contentHistoryChangelistWatchers[(pid, manifestId)];
		watcher.BeginInit();
		watcher.Path = changelistsFolder;
		watcher.IncludeSubdirectories = true;
		watcher.Filter = "*.json";
		watcher.EnableRaisingEvents = true;
		watcher.NotifyFilter = (NotifyFilters.Attributes |
		                        NotifyFilters.CreationTime |
		                        NotifyFilters.DirectoryName |
		                        NotifyFilters.FileName |
		                        NotifyFilters.LastWrite |
		                        NotifyFilters.LastAccess);
		watcher.Error += (_, e) => Log.Error(e.GetException().ToString());
		watcher.Disposed += (_, e) => Log.Error($"Disposed {e}");
		watcher.Created += (_, e) => { OnFilesChanged(e); };
		watcher.Deleted += (_, e) => { OnFilesChanged(e); };
		watcher.Renamed += (_, e) => { OnFilesChanged(e); };
		watcher.Changed += (_, e) => { OnFilesChanged(e); };
		watcher.EndInit();

		// Keep waiting for messages from the set up file watcher.
		var reader = _channelContentHistoryChangelists.Reader;

		while (true)
		{
			if (token.IsCancellationRequested)
			{
				break;
			}

			try
			{
				await reader.WaitToReadAsync(token);
				await Task.Delay(100, token);
			}
			catch (OperationCanceledException)
			{
				Log.Debug($"{nameof(ListenToContentHistoryChangelists)} was cancelled");
				break;
			}

			var batchedChanges = new LocalContentHistoryChangelistFileChanges() { AllFileChanges = new() };
			while (reader.TryRead(out var changed))
			{
				batchedChanges.AllFileChanges.Add(changed);
			}

			yield return batchedChanges;
		}

		yield break;

		void OnFilesChanged(FileSystemEventArgs e)
		{
			var lastWriteTime = new DateTimeOffset(File.GetLastWriteTime(e.FullPath)).ToUnixTimeMilliseconds();
			var lastAccessTime = new DateTimeOffset(File.GetLastAccessTime(e.FullPath)).ToUnixTimeMilliseconds();
			if (e.ChangeType == WatcherChangeTypes.Created)
			{
				var changed = new ChangedContentHistoryChangelistFile { OwnerPid = pid };
				changed.OwnerPid = pid;
				changed.OwnerManifestId = manifestId;

				changed.ManifestUid = Path.GetFileNameWithoutExtension(e.Name) ?? "";
				changed.FullFilePath = e.FullPath;
				changed.OldFullFilePath = "";
				changed.OldManifestUid = "";

				if (!eventDisambiguationHelper.TryGetValue(e.FullPath, out var time) || time != lastWriteTime)
				{
					eventDisambiguationHelper[e.FullPath] = lastWriteTime;
					Log.Verbose($"Created changelist file ({lastWriteTime}): {JsonConvert.SerializeObject(changed)} ");
					_channelContentHistoryChangelists.Writer.TryWrite(changed);
				}
			}
			else if (e.ChangeType == WatcherChangeTypes.Deleted)
			{
				var changed = new ChangedContentHistoryChangelistFile { OwnerPid = pid };
				changed.OwnerPid = pid;
				changed.OwnerManifestId = manifestId;

				changed.ManifestUid = "";
				changed.OldManifestUid = Path.GetFileNameWithoutExtension(e.Name) ?? "";
				changed.FullFilePath = "";
				changed.OldFullFilePath = e.FullPath;
				Log.Verbose($"Deleted changelist file: {JsonConvert.SerializeObject(changed)} ");
				_channelContentHistoryChangelists.Writer.TryWrite(changed);
			}
			else if (e.ChangeType == WatcherChangeTypes.Changed)
			{
				var changed = new ChangedContentHistoryChangelistFile { OwnerPid = pid };
				changed.OwnerPid = pid;
				changed.OwnerManifestId = manifestId;

				changed.ManifestUid = Path.GetFileNameWithoutExtension(e.Name) ?? "";
				changed.OldManifestUid = changed.ManifestUid;
				changed.FullFilePath = changed.OldFullFilePath = e.FullPath;

				// Check if this is a read access change (access time changed but write time didn't)
				var accessKey = $"{e.FullPath}_access";
				var writeKey = e.FullPath;

				bool accessChanged = !eventDisambiguationHelper.TryGetValue(accessKey, out var lastKnownAccessTime) || lastKnownAccessTime != lastAccessTime;
				bool writeChanged = !eventDisambiguationHelper.TryGetValue(writeKey, out var lastKnownWriteTime) || lastKnownWriteTime != lastWriteTime;

				if (accessChanged && !writeChanged)
				{
					// Only access time changed - this is a read
					changed.WasReadAccessed = true;
					eventDisambiguationHelper[accessKey] = lastAccessTime;
					Log.Verbose($"Read changelist file ({lastAccessTime}): {JsonConvert.SerializeObject(changed)} ");
					_channelContentHistoryChangelists.Writer.TryWrite(changed);
				}
				else if (writeChanged)
				{
					// Write time changed - this is a modification
					changed.WasReadAccessed = false;
					eventDisambiguationHelper[writeKey] = lastWriteTime;
					eventDisambiguationHelper[accessKey] = lastAccessTime;
					Log.Verbose($"Changed changelist file ({lastWriteTime}): {JsonConvert.SerializeObject(changed)} ");
					_channelContentHistoryChangelists.Writer.TryWrite(changed);
				}
			}
			else if (e.ChangeType == WatcherChangeTypes.Renamed)
			{
				if (e is RenamedEventArgs renamedEventArgs)
				{
					var renamed = new ChangedContentHistoryChangelistFile();
					renamed.OwnerPid = pid;
					renamed.OwnerManifestId = manifestId;
					renamed.ManifestUid = Path.GetFileNameWithoutExtension(renamedEventArgs.Name) ?? "";
					renamed.OldManifestUid = Path.GetFileNameWithoutExtension(renamedEventArgs.OldName) ?? "";
					renamed.FullFilePath = renamedEventArgs.FullPath;
					renamed.OldFullFilePath = renamedEventArgs.OldFullPath;
					Log.Verbose($"Renamed changelist file: {JsonConvert.SerializeObject(renamed)} ");

					_channelContentHistoryChangelists.Writer.TryWrite(renamed);
				}
			}
		}
	}


	/// <summary>
	/// Synchronizes content history entries from the remote Beamable API to local storage, fetching only new entries not already cached.
	/// Walks backwards through history in pages until all new entries are downloaded or cancellation occurs.
	/// Invokes an optional progress callback after each page is processed.
	/// </summary>
	/// <param name="pid">The realm id (PID) to sync entries for</param>
	/// <param name="manifestId">The manifest ID to sync, defaults to "global"</param>
	/// <param name="onProgress">Optional callback invoked after each page is fetched and saved, receiving a report of the newly fetched entries</param>
	/// <param name="cancellationToken">Cancellation token to abort the sync operation</param>
	/// <returns>A ContentHistoryFetchReport containing all entries fetched during this sync session</returns>
	/// <remarks>
	/// Edge cases:
	/// - Uses semaphore to prevent file system races during concurrent writes
	/// - Skips entries that already exist locally (based on CreatedDate)
	/// - Starts from the current time or continues from the oldest local entry (localStartDate - 1)
	/// - Stops when hasMore=false or when minCreatedInPage doesn't advance (all pages exhausted)
	/// - Logs errors for individual entry save failures but continues with remaining entries
	/// - Returns partial results if cancellation occurs mid-sync
	/// - Page limit is hardcoded to 100 entries per API call
	/// </remarks>
	public async Task<ContentHistoryFetchReport> SyncContentHistoryEntries(string pid, string manifestId = "global", Action<ContentHistoryFetchReport> onProgress = null, CancellationToken cancellationToken = default)
	{
		// Ensure local entries folder exists
		var entriesPath = EnsureContentHistoryEntriesFolderExists(out _, pid, manifestId);

		// Load locally cached entries so we can avoid re-fetching duplicates and determine where to continue from
		var allLocallyCachedEntries = await GetAllContentHistoryLocalEntries(pid, manifestId);
		var existingCreatedDates = new HashSet<long>();
		long? localStartDate = null;
		if (allLocallyCachedEntries.Entries.Count > 0)
		{
			existingCreatedDates.UnionWith(allLocallyCachedEntries.Entries.Select(e => e.CreatedDate));
			localStartDate = allLocallyCachedEntries.StartDate;
		}

		// Collector for all entries we actually fetched during this call
		var allFetchedEntries = new List<ContentHistoryEntry>();

		int greedyPageLimit = 100;
		bool hasMore = true;
		long toDateCursor = localStartDate.HasValue ? localStartDate.Value - 1 : DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();

		try
		{
			while (hasMore && !cancellationToken.IsCancellationRequested)
			{
				var fetchResult = await _contentApi.GetManifestDiffs(manifestId, toDate: toDateCursor, limit: greedyPageLimit, offset: 0);

				long minCreatedInPage = long.MaxValue;
				var pageEntries = new List<ContentHistoryEntry>();

				// Acquire entries semaphore while writing files for this page to avoid races with readers/listeners
				await _contentHistoryEntriesFileSystemSemaphore.WaitAsync(cancellationToken);
				try
				{
					foreach (var diff in fetchResult.diffs)
					{
						if (diff == null) continue;
						var createdDate = diff.createdDate;
						minCreatedInPage = Math.Min(minCreatedInPage, createdDate);
						if (existingCreatedDates.Contains(createdDate)) continue;

						var entry = ContentHistoryEntry.FromManifestDiff(diff);

						var entryFileName = ChangedContentHistoryEntryFile.BuildEntryFileName(entry.CreatedDate, entry.ManifestUid);
						var fileName = Path.Combine(entriesPath, $"{entryFileName}.json");
						try
						{
							var json = JsonSerializer.Serialize(entry, GetContentFileSerializationOptions());
							await DirectoryUtils.WriteUtf8FileAsync(fileName, json, cancellationToken);

							existingCreatedDates.Add(createdDate);
							pageEntries.Add(entry);
							allFetchedEntries.Add(entry);
						}
						catch (Exception e)
						{
							Log.Error(e, $"Failed to save content history entry for createdDate={createdDate}");
						}
					}
				}
				finally
				{
					_contentHistoryEntriesFileSystemSemaphore.Release();
				}

				// Report progress for this page
				if (onProgress != null)
				{
					onProgress(new ContentHistoryFetchReport() { Entries = pageEntries });
				}

				// Prepare cursor for next page: go strictly older than the minimum createdDate we saw
				if (minCreatedInPage == long.MaxValue)
				{
					hasMore = false;
				}
				else
				{
					toDateCursor = minCreatedInPage - 1;
					hasMore = fetchResult.hasMore;
				}
			}
		}
		catch (OperationCanceledException)
		{
			Log.Debug($"{nameof(SyncContentHistoryEntries)} was cancelled");
		}

		// Return a report containing all fetched entries
		return new ContentHistoryFetchReport() { Entries = allFetchedEntries };
	}

	/// <summary>
	/// Loads all locally cached content history entries from disk, with optional filtering by date range and manifest UIDs.
	/// Files are filtered by filename pattern before deserialization for efficiency.
	/// Entries are sorted by CreatedDate in descending order (most recent first).
	/// </summary>
	/// <param name="pid">The realm id (PID) whose entries to load</param>
	/// <param name="manifest">The manifest ID, defaults to "global"</param>
	/// <param name="startDate">Optional minimum CreatedDate (inclusive) to filter by</param>
	/// <param name="endDate">Optional maximum CreatedDate (inclusive) to filter by</param>
	/// <param name="manifestUids">Optional collection of manifest UIDs to filter by (if provided, only matching entries are loaded)</param>
	/// <returns>
	/// A ContentHistoryEntriesPage containing all matching entries, sorted by CreatedDate descending (newest first).
	/// StartDate field contains the oldest CreatedDate (last entry), EndDate field contains the newest CreatedDate (first entry).
	/// ContainedManifestUids array contains all unique manifest UIDs in the result set.
	/// </returns>
	/// <remarks>
	/// Edge cases:
	/// - Uses semaphore to prevent concurrent file system access
	/// - Retries file reads in a busy-wait loop if IOException occurs (file locked by another process)
	/// - Returns empty page if no entries match the filters
	/// - Throws if any entry file fails to deserialize (logs errors for AggregateException)
	/// - All files must have .json extension
	/// - Filename parsing must succeed for TryParseEntryFileName, otherwise file is skipped
	/// </remarks>
	public async Task<ContentHistoryEntriesPage> GetAllContentHistoryLocalEntries(string pid, string manifest = "global", long? startDate = null, long? endDate = null, IEnumerable<string> manifestUids = null)
	{
		// Ensure exclusive access while reading existing entry files to avoid races with writers
		await _contentHistoryEntriesFileSystemSemaphore.WaitAsync();
		try
		{
			var localEntriesPage = new ContentHistoryEntriesPage();
			var entriesPath = EnsureContentHistoryEntriesFolderExists(out _, pid, manifest);

			// Convert manifestUids to HashSet for O(1) lookups if provided
			var uidsFilter = manifestUids != null ? new HashSet<string>(manifestUids) : null;

			var tasks =
				// For each existing file inside the content folder we care about, we'll have one entry.
				Directory.EnumerateFiles(entriesPath)
					// Only get the JSON files
					.Where(fp => Path.GetExtension(fp).EndsWith("json"))
					// Filter by date range and UIDs based on filename before reading/deserializing
					.Where(fp =>
					{
						var fileNameWithoutExt = Path.GetFileNameWithoutExtension(fp);
						if (!ChangedContentHistoryEntryFile.TryParseEntryFileName(fileNameWithoutExt, out var createdDate, out var uid))
							return false;

						// Apply date range filter
						if (startDate.HasValue && createdDate < startDate.Value)
							return false;
						if (endDate.HasValue && createdDate > endDate.Value)
							return false;

						// Apply UID filter
						if (uidsFilter != null && !uidsFilter.Contains(uid))
							return false;

						return true;
					})
					// Load the files that passed the filter into memory
					.Select(async fp =>
					{
						// We got to do this so that we don't collide with other software editing the files on disk.
						var text = "";
						var readText = false;
						while (!readText || text == "")
						{
							try
							{
								text = await File.ReadAllTextAsync(fp);
								readText = true;
							}
							catch (IOException)
							{
								readText = false;
								text = "";
							}
						}

						try
						{
							var json = JsonSerializer.Deserialize<JsonElement>(text, GetContentFileSerializationOptions());
							var entryFile = new ContentHistoryEntry()
							{
								ManifestUid = json.GetProperty(ContentHistoryEntry.JSON_PROP_MANIFEST_UID).GetString(),
								CreatedDate = json.GetProperty(ContentHistoryEntry.JSON_PROP_CREATED_DATE).GetInt64(),
								PublishedBy = json.GetProperty(ContentHistoryEntry.JSON_PROP_PUBLISHED_BY).GetString() ?? "",
								PublishedByName = json.GetProperty(ContentHistoryEntry.JSON_PROP_PUBLISHED_BY_NAME).GetString() ?? "",
								AffectedContentIds = json.TryGetProperty(ContentHistoryEntry.JSON_PROP_AFFECTED_CONTENT_IDS, out var affectedContentIds)
									? affectedContentIds.EnumerateArray().Select(e => e.GetString()).ToArray()
									: Array.Empty<string>(),
							};

							return entryFile;
						}
						catch (Exception e)
						{
							Log.Error(e, $"Error when loading content history entry file {fp}");
							throw;
						}
					}).ToList();

			// Wait for all the content file tasks and return the list of ContentHistoryEntry.
			try
			{
				localEntriesPage.Entries = (await Task.WhenAll(tasks)).ToList();
				if (localEntriesPage.Entries.Count > 0)
				{
					localEntriesPage.Entries.Sort((e1, e2) => e2.CreatedDate.CompareTo(e1.CreatedDate)); // Descending order (most recent first)
					localEntriesPage.ContainedManifestUids = localEntriesPage.Entries.Select(e => e.ManifestUid).ToArray();
					localEntriesPage.StartDate = localEntriesPage.Entries.Last().CreatedDate; // Last is oldest
					localEntriesPage.EndDate = localEntriesPage.Entries.First().CreatedDate; // First is newest
				}

				return localEntriesPage;
			}
			catch (Exception e)
			{
				if (e is AggregateException ae)
				{
					foreach (var aeInnerException in ae.InnerExceptions)
					{
						Log.Error(aeInnerException, "Error when loading content history entry files");
					}
				}

				throw;
			}
		}
		finally
		{
			_contentHistoryEntriesFileSystemSemaphore.Release();
		}
	}


	/// <summary>
	/// Synchronizes content history changelists from the remote Beamable CDN to local storage, downloading only changelists that aren't already cached.
	/// Loads local entries to determine changelist URLs, filters out already-cached changelists, downloads remaining ones in parallel, and saves them to disk.
	/// Post-processes each changelist to normalize null values, compute file paths, and extract metadata.
	/// </summary>
	/// <param name="pid">The realm id (PID) to sync changelists for</param>
	/// <param name="manifestId">The manifest ID to sync</param>
	/// <param name="manifestUids">The collection of manifest UIDs whose changelists should be synced</param>
	/// <param name="cancellationToken">Cancellation token to abort the sync operation</param>
	/// <returns>A ContentHistoryChangelistPage containing all changelists downloaded during this sync session</returns>
	/// <remarks>
	/// Edge cases:
	/// - Uses semaphore to prevent file system races during concurrent writes
	/// - Skips changelists that already exist locally
	/// - Only downloads changelists for UIDs that have corresponding entries in the local cache
	/// - Downloads all changelists in parallel using Task.WhenAll
	/// - Replaces null Created/Removed/Modified dictionaries with empty dictionaries
	/// - Normalizes all string fields in changelist entries to empty strings if null (to avoid null checks downstream)
	/// - Computes JsonFilePath as relative path from Beamable workspace
	/// - Parses content ID to extract TypeName and Name (splits on last '.' character)
	/// - Sets ChangeStatus based on which dictionary the entry appears in (Created/Modified/Removed)
	/// - Logs errors for individual download/save failures and throws to propagate the exception
	/// - Returns partial results if cancellation occurs mid-sync
	/// </remarks>
	public async Task<ContentHistoryChangelistPage> SyncContentHistoryChangelists(string pid, string manifestId, IEnumerable<string> manifestUids, CancellationToken cancellationToken = default)
	{
		// Ensure local changelists folder exists
		var changelistsPath = EnsureContentHistoryChangelistsFolderExists(out _, pid, manifestId);

		// Convert the enumeration to a HashSet for faster lookups
		var desiredUids = new HashSet<string>(manifestUids);

		// Load locally cached entries to find the changelist URLs
		var allLocallyCachedEntries = await GetAllContentHistoryLocalEntries(pid, manifestId);
		var changelistUrlsByUid = new Dictionary<string, string>();

		if (allLocallyCachedEntries?.Entries != null)
		{
			foreach (var entry in allLocallyCachedEntries.Entries)
			{
				if (desiredUids.Contains(entry.ManifestUid))
				{
					changelistUrlsByUid[entry.ManifestUid] = GetContentHistoryChangelistUrl(_requester.Cid, _requester.Pid, entry);
				}
			}
		}

		// Load locally cached changelists to exclude entries that are already stored
		var allLocallyCachedChangelists = await GetAllContentHistoryLocalChangelists(pid, manifestId);
		var localChangelistUids = new HashSet<string>();

		if (allLocallyCachedChangelists?.Changelists != null)
		{
			foreach (var changelist in allLocallyCachedChangelists.Changelists)
			{
				localChangelistUids.Add(changelist.ManifestUid);
			}
		}

		// Determine which changelists need to be downloaded
		var changelistsToDownload = new List<string>();
		foreach (var uid in desiredUids)
		{
			if (!localChangelistUids.Contains(uid) && changelistUrlsByUid.ContainsKey(uid))
			{
				changelistsToDownload.Add(uid);
			}
		}

		// Collector for all changelists we actually downloaded during this call
		var downloadedChangelists = new List<ContentHistoryChangelist>();

		try
		{
			// Download the changelist JSON files
			var downloadTasks = changelistsToDownload.Select(async uid =>
			{
				try
				{
					var url = changelistUrlsByUid[uid];
					var changelist = await _requester.CustomRequest<ContentHistoryChangelist>(Method.GET, url,
						parser: (jsonString) => JsonSerializer.Deserialize<ContentHistoryChangelist>(jsonString, GetContentFileSerializationOptions()));

					return (uid, changelist);
				}
				catch (Exception e)
				{
					Log.Error(e, $"Failed to download content history changelist for uid={uid}");
					throw;
				}
			}).ToList();

			var downloadResults = await Task.WhenAll(downloadTasks);

			// Acquire changelists semaphore while writing files to avoid races with readers/listeners
			await _contentHistoryChangelistsFileSystemSemaphore.WaitAsync(cancellationToken);
			try
			{
				foreach (var (uid, changelist) in downloadResults)
				{
					var fixedChangelist = changelist;
					fixedChangelist.ManifestUid = uid;

					// We make sure we don't store "null"s here ---
					// this is just to make it so that we don't need to null check and because UE's JSON library emits an annoying warning when it tries to get a string out of a "null".
					fixedChangelist.Created ??= new();
					fixedChangelist.Removed ??= new();
					fixedChangelist.Modified ??= new();

					// Compute the base path for content files in this manifest
					var contentBasePath = Path.Combine(ContentHistoryContentPath, pid, manifestId, uid);

					void PostProcessEntry(Dictionary<string, ContentHistoryChangelistEntry> dict, ContentStatus changeStatus)
					{
						foreach (string key in dict.Keys)
						{
							var e = dict[key];
							e.OldVersion ??= "";
							e.OldChecksum ??= "";
							e.OldTags ??= Array.Empty<string>();
							e.NewVersion ??= "";
							e.NewChecksum ??= "";
							e.NewTags ??= Array.Empty<string>();
							// Compute the expected local file path for this content (relative to BeamableWorkspace)
							var absolutePath = Path.Combine(contentBasePath, $"{key}.json");
							e.JsonFilePath = Path.GetRelativePath(_config.BeamableWorkspace, absolutePath);
							// Compute metadata fields
							e.FullId = key;
							// Split content ID (e.g., "items.MyItem") into type ("items") and name ("MyItem")
							var lastDotIndex = key.LastIndexOf('.');
							if (lastDotIndex > 0)
							{
								e.TypeName = key.Substring(0, lastDotIndex);
								e.Name = key.Substring(lastDotIndex + 1);
							}
							else
							{
								e.TypeName = "";
								e.Name = key;
							}

							e.ChangeStatus = (int)changeStatus;
							e.ChangeDate = fixedChangelist.PublishedAt;
							dict[key] = e;
						}
					}

					PostProcessEntry(fixedChangelist.Created, ContentStatus.Created);
					PostProcessEntry(fixedChangelist.Removed, ContentStatus.Deleted);
					PostProcessEntry(fixedChangelist.Modified, ContentStatus.Modified);

					var fileName = Path.Combine(changelistsPath, $"{uid}.json");
					try
					{
						var json = JsonSerializer.Serialize(fixedChangelist, GetContentFileSerializationOptions());
						await DirectoryUtils.WriteUtf8FileAsync(fileName, json, cancellationToken);

						downloadedChangelists.Add(fixedChangelist);
					}
					catch (Exception e)
					{
						Log.Error(e, $"Failed to save content history changelist for uid={uid}");
					}
				}
			}
			finally
			{
				_contentHistoryChangelistsFileSystemSemaphore.Release();
			}
		}
		catch (OperationCanceledException)
		{
			Log.Debug($"{nameof(SyncContentHistoryChangelists)} was cancelled");
		}

		// Return a page containing the downloaded changelists
		return new ContentHistoryChangelistPage() { Changelists = downloadedChangelists.ToArray() };
	}

	/// <summary>
	/// Loads all locally cached content history changelists from disk, with optional filtering by manifest UIDs.
	/// Files are filtered by filename before deserialization for efficiency.
	/// Changelists are sorted by PublishedAt in ascending order.
	/// Converts all JsonFilePath entries from relative to absolute paths.
	/// </summary>
	/// <param name="pid">The realm id (PID) whose changelists to load</param>
	/// <param name="manifest">The manifest ID, defaults to "global"</param>
	/// <param name="manifestUids">Optional collection of manifest UIDs to filter by (if provided, only matching changelists are loaded)</param>
	/// <returns>
	/// A ContentHistoryChangelistPage containing all matching changelists, sorted by PublishedAt ascending.
	/// All JsonFilePath values in changelist entries are converted to absolute paths.
	/// </returns>
	/// <remarks>
	/// Edge cases:
	/// - Uses semaphore to prevent concurrent file system access
	/// - Retries file reads in a busy-wait loop if IOException occurs (file locked by another process)
	/// - Returns empty page if no changelists match the filters
	/// - Throws if any changelist file fails to deserialize (logs errors for AggregateException)
	/// - All files must have .json extension
	/// - Filename (without extension) is treated as the manifest UID
	/// - Converts relative JsonFilePath to absolute by combining with BeamableWorkspace path
	/// - Processes Created, Modified, and Removed dictionaries independently
	/// </remarks>
	public async Task<ContentHistoryChangelistPage> GetAllContentHistoryLocalChangelists(string pid, string manifest = "global", IEnumerable<string> manifestUids = null)
	{
		// Ensure exclusive access while reading existing changelist files to avoid races with writers
		await _contentHistoryChangelistsFileSystemSemaphore.WaitAsync();
		try
		{
			var localChangelistsPage = new ContentHistoryChangelistPage();
			var changelistsPath = EnsureContentHistoryChangelistsFolderExists(out _, pid, manifest);

			// Convert manifestUids to HashSet for O(1) lookups if provided
			var uidsFilter = manifestUids != null ? new HashSet<string>(manifestUids) : null;

			var tasks =
				// For each existing file inside the changelists folder we care about, we'll have one changelist.
				Directory.EnumerateFiles(changelistsPath)
					// Only get the JSON files
					.Where(fp => Path.GetExtension(fp).EndsWith("json"))
					// Filter by manifest UID based on filename before reading/deserializing
					.Where(fp =>
					{
						if (uidsFilter == null) return true;
						var fileNameWithoutExt = Path.GetFileNameWithoutExtension(fp);
						return uidsFilter.Contains(fileNameWithoutExt);
					})
					// Load the files that passed the filter into memory
					.Select(async fp =>
					{
						// We got to do this so that we don't collide with other software editing the files on disk.
						var text = "";
						var readText = false;
						while (!readText || text == "")
						{
							try
							{
								text = await File.ReadAllTextAsync(fp);
								readText = true;
							}
							catch (IOException)
							{
								readText = false;
								text = "";
							}
						}

						try
						{
							var changelist = JsonSerializer.Deserialize<ContentHistoryChangelist>(text, GetContentFileSerializationOptions());
							return changelist;
						}
						catch (Exception e)
						{
							Log.Error(e, $"Error when loading content history changelist file {fp}");
							throw;
						}
					}).ToList();

			// Wait for all the changelist file tasks and return the list of ContentHistoryChangelist.
			try
			{
				localChangelistsPage.Changelists = (await Task.WhenAll(tasks)).ToArray();
				if (localChangelistsPage.Changelists != null && localChangelistsPage.Changelists.Length > 0)
				{
					// Sort by PublishedAt in ascending order
					System.Array.Sort(localChangelistsPage.Changelists, (c1, c2) => c1.PublishedAt.CompareTo(c2.PublishedAt));

					// Convert relative JsonFilePath to absolute path for each entry
					for (int i = 0; i < localChangelistsPage.Changelists.Length; i++)
					{
						var changelist = localChangelistsPage.Changelists[i];

						void ConvertToAbsolutePath(Dictionary<string, ContentHistoryChangelistEntry> dict)
						{
							if (dict == null) return;
							foreach (string key in dict.Keys)
							{
								var e = dict[key];
								if (!string.IsNullOrEmpty(e.JsonFilePath))
								{
									e.JsonFilePath = Path.Combine(_config.BeamableWorkspace, e.JsonFilePath);
									dict[key] = e;
								}
							}
						}

						ConvertToAbsolutePath(changelist.Created);
						ConvertToAbsolutePath(changelist.Modified);
						ConvertToAbsolutePath(changelist.Removed);

						localChangelistsPage.Changelists[i] = changelist;
					}
				}

				return localChangelistsPage;
			}
			catch (Exception e)
			{
				if (e is AggregateException ae)
				{
					foreach (var aeInnerException in ae.InnerExceptions)
					{
						Log.Error(aeInnerException, "Error when loading content history changelist files");
					}
				}

				throw;
			}
		}
		finally
		{
			_contentHistoryChangelistsFileSystemSemaphore.Release();
		}
	}


	/// <summary>
	/// Loads all locally cached content files from disk for a specific manifest UID, with optional filtering by content IDs.
	/// Retrieves the corresponding changelist to enrich content entries with changelist metadata.
	/// Converts each ContentFile to a ContentHistoryChangelistContentEntry with full metadata.
	/// </summary>
	/// <param name="pid">The realm id (PID) whose content to load</param>
	/// <param name="manifestId">The manifest ID, defaults to "global"</param>
	/// <param name="manifestUid">The specific manifest UID subfolder to load content from (empty string loads from root, but this will likely fail)</param>
	/// <param name="contentIds">Optional collection of content IDs to filter by (if provided, only matching content files are loaded based on filename)</param>
	/// <returns>
	/// A ContentHistoryContentPage containing all matching content entries, each enriched with changelist metadata.
	/// </returns>
	/// <remarks>
	/// Edge cases:
	/// - Uses semaphore to prevent concurrent file system access
	/// - Throws CliException if manifestUid is specified but the directory doesn't exist
	/// - Returns empty page if no changelists exist for the manifestUid
	/// - Only processes the first changelist in the result (assumes one changelist per manifestUid)
	/// - Returns empty page if no content files match the filters
	/// - Filters by content ID based on filename (without extension) before loading
	/// - Searches for changelist entry in Created, Modified, then Removed dictionaries (in that order)
	/// - Converts each ContentFile to ContentHistoryChangelistContentEntry via helper function
	/// - Throws if any content file fails to deserialize (logs errors for AggregateException)
	/// - All files must have .json extension
	/// </remarks>
	public async Task<ContentHistoryContentPage> GetAllContentHistoryLocalContent(string pid, string manifestId = "global", string manifestUid = "", IEnumerable<string> contentIds = null)
	{
		// Ensure exclusive access while reading existing content files to avoid races with writers
		await _contentHistoryContentFileSystemSemaphore.WaitAsync();
		try
		{
			var localContentPage = new ContentHistoryContentPage();

			// If manifestUid is specified, look only in that subfolder
			var contentPath = EnsureContentHistoryContentFolderExists(out _, pid, manifestId);
			var searchPath = string.IsNullOrEmpty(manifestUid) ? contentPath : Path.Combine(contentPath, manifestUid);

			// If we're looking for a specific manifest UID but it doesn't exist, return empty page
			if (!string.IsNullOrEmpty(manifestUid) && !Directory.Exists(searchPath))
			{
				throw new CliException("");
			}

			// Load the changelist for this manifestUid to get the changelist entries
			var changelists = await GetAllContentHistoryLocalChangelists(pid, manifestId, new[] { manifestUid });
			if (changelists.Changelists == null || changelists.Changelists.Length == 0)
			{
				localContentPage.ContentEntries = new List<ContentHistoryChangelistContentEntry>();
				return localContentPage;
			}

			var changelist = changelists.Changelists[0];

			// Convert contentIds to HashSet for O(1) lookups if provided
			var contentIdsFilter = contentIds != null ? new HashSet<string>(contentIds) : null;

			var tasks = new List<Task<(string contentId, ContentFile file)>>();

			// If manifestUid is specified, search in that folder only
			tasks.AddRange(Directory.EnumerateFiles(searchPath)
				.Where(fp => Path.GetExtension(fp).EndsWith("json"))
				// Filter by content ID based on filename before reading/deserializing
				.Where(fp =>
				{
					if (contentIdsFilter == null) return true;
					var fileNameWithoutExt = Path.GetFileNameWithoutExtension(fp);
					return contentIdsFilter.Contains(fileNameWithoutExt);
				})
				.Select(fp => LoadContentFileAsync(fp)));

			// If no tasks, return an empty page
			if (tasks.Count == 0)
			{
				localContentPage.ContentEntries = new List<ContentHistoryChangelistContentEntry>();
				return localContentPage;
			}

			// Wait for all the content file tasks and convert to ContentHistoryChangelistContentEntry
			try
			{
				var contentFiles = await Task.WhenAll(tasks);
				localContentPage.ContentEntries = contentFiles.Select(x =>
				{
					var file = x.file;

					// Find the changelist entry for this content
					ContentHistoryChangelistEntry changelistEntry = default;
					if (changelist.Created?.ContainsKey(file.Id) == true) changelistEntry = changelist.Created[file.Id];
					else if (changelist.Modified?.ContainsKey(file.Id) == true) changelistEntry = changelist.Modified[file.Id];
					else if (changelist.Removed?.ContainsKey(file.Id) == true) changelistEntry = changelist.Removed[file.Id];

					return ContentFileToContentHistoryChangelistContentEntry(file, changelist, changelistEntry);
				}).ToList();
				return localContentPage;
			}
			catch (Exception e)
			{
				if (e is AggregateException ae)
				{
					foreach (var aeInnerException in ae.InnerExceptions)
					{
						Log.Error(aeInnerException, "Error when loading content history content files");
					}
				}

				throw;
			}
		}
		finally
		{
			_contentHistoryContentFileSystemSemaphore.Release();
		}
	}

	/// <summary>
	/// Synchronizes content history content files from the remote Beamable CDN to local storage, downloading only content files that aren't already cached.
	/// Fetches the realm information to get the root PID, loads the corresponding changelist, determines which content files need to be downloaded,
	/// downloads them in parallel from the CDN, and saves them to disk with proper metadata.
	/// </summary>
	/// <param name="pid">The realm id (PID) to sync content for</param>
	/// <param name="manifestId">The manifest ID to sync</param>
	/// <param name="manifestUid">The specific manifest UID whose content files should be synced</param>
	/// <param name="contentIds">The collection of content IDs to sync</param>
	/// <param name="cancellationToken">Cancellation token to abort the sync operation</param>
	/// <returns>A ContentHistoryContentPage containing all content files downloaded during this sync session</returns>
	/// <remarks>
	/// Edge cases:
	/// - Uses semaphore to prevent file system races during concurrent writes
	/// - Creates manifestUid subfolder if it doesn't exist
	/// - Returns empty page if no changelist exists for the manifestUid
	/// - Skips content IDs that already exist locally
	/// - Downloads all content files in parallel using Task.WhenAll
	/// - Handles removed content by using GetContentHistoryContentOldUrl (OldChecksum)
	/// - Handles created/modified content by using GetContentHistoryContentNewUrl (NewChecksum)
	/// - Logs warning if content ID is not found in any dictionary (Created/Modified/Removed)
	/// - Logs errors for individual download/save failures and throws to propagate the exception
	/// - Returns partial results if cancellation occurs mid-sync
	/// - Converts each downloaded ContentFile to ContentHistoryChangelistContentEntry before returning
	/// - Skips entries with empty contentId after download
	/// </remarks>
	public async Task<ContentHistoryContentPage> SyncContentHistoryContent(string pid, string manifestId, string manifestUid, IEnumerable<string> contentIds, CancellationToken cancellationToken = default)
	{
		// Fetch the realm information to get the root PID
		var currentRealmPromise = _realmsApi.GetRealm();

		// Ensure local content folder exists
		var contentPath = EnsureContentHistoryContentFolderExists(out _, pid, manifestId);
		var manifestUuidFolder = Path.Combine(contentPath, manifestUid);
		if (!Directory.Exists(manifestUuidFolder))
		{
			Directory.CreateDirectory(manifestUuidFolder);
		}

		// Convert the enumeration to a HashSet for faster lookups
		var desiredContentIds = new HashSet<string>(contentIds);

		// Load locally cached changelists to find the target changelist
		// If we don't have a changelist for this manifestUid, we can't download content
		var changelists = await GetAllContentHistoryLocalChangelists(pid, manifestId);
		ContentHistoryChangelist targetChangelist = changelists.Changelists.FirstOrDefault(c => c.ManifestUid == manifestUid);
		if (string.IsNullOrEmpty(targetChangelist.ManifestUid)) return new ContentHistoryContentPage() { ContentEntries = new List<ContentHistoryChangelistContentEntry>() };

		// Load locally cached content to exclude files that are already stored
		var allLocalContent = await GetAllContentHistoryLocalContent(pid, manifestId, manifestUid);
		var localContentIds = allLocalContent.ContentEntries.Select(c => c.FullId);

		// Determine which content files need to be downloaded
		var contentIdsToDownload = desiredContentIds.Except(localContentIds);

		// Fetch the Root PID
		var currentRealm = await currentRealmPromise;
		var rootPid = currentRealm.GamePid;

		// Download the content JSON files from the changelist
		var downloadedContent = new List<ContentHistoryChangelistContentEntry>();
		try
		{
			var downloadTasks = contentIdsToDownload.Select(async contentId =>
			{
				try
				{
					// Find the content entry in the changelist
					ContentHistoryChangelistEntry entry = default;
					bool found = false;
					bool isRemoved = false;

					// Check Created dictionary first
					if (targetChangelist.Created != null && targetChangelist.Created.TryGetValue(contentId, out var createdEntry))
					{
						entry = createdEntry;
						found = true;
					}
					// Check Modified dictionary
					else if (targetChangelist.Modified != null && targetChangelist.Modified.TryGetValue(contentId, out var modifiedEntry))
					{
						entry = modifiedEntry;
						found = true;
					}
					// Check Removed dictionary - we CAN download removed content using OldUrl
					else if (targetChangelist.Removed != null && targetChangelist.Removed.TryGetValue(contentId, out var removedEntry))
					{
						entry = removedEntry;
						found = true;
						isRemoved = true;
					}

					if (!found)
					{
						Log.Warning($"Content {contentId} not found in changelist for manifest {manifestUid}");
						return default;
					}

					// Generate the content URL using the appropriate static function
					// For removed entries, use OldUrl; for created/modified entries, use NewUrl
					var uri = isRemoved
						? GetContentHistoryContentOldUrl(_requester.Cid, rootPid, contentId, entry)
						: GetContentHistoryContentNewUrl(_requester.Cid, rootPid, contentId, entry);

					var contentFile = await _requester.CustomRequest<ContentFile>(Method.GET, uri,
						parser: (jsonString) => JsonSerializer.Deserialize<ContentFile>(jsonString, GetContentFileSerializationOptions()));

					contentFile.Id = contentId;
					contentFile.FetchedFromManifestUid = manifestUid;
					contentFile.Tags = JsonSerializer.SerializeToElement(isRemoved ? entry.OldTags : entry.NewTags);
					contentFile.PropertiesChecksum = isRemoved ? entry.OldChecksum : entry.NewChecksum;

					return (contentFile, entry);
				}
				catch (Exception e)
				{
					Log.Error(e, $"Failed to download content history content for contentId={contentId}");
					throw;
				}
			}).ToList();

			var downloadResults = await Task.WhenAll(downloadTasks);

			// Acquire content semaphore while writing files to avoid races with readers/listeners
			await _contentHistoryContentFileSystemSemaphore.WaitAsync(cancellationToken);
			try
			{
				foreach (var (contentFile, changelistEntry) in downloadResults)
				{
					var contentId = contentFile.Id;
					if (string.IsNullOrEmpty(contentId)) continue;

					var fileName = Path.Combine(manifestUuidFolder, $"{contentId}.json");
					try
					{
						var json = JsonSerializer.Serialize(contentFile, GetContentFileSerializationOptions());
						await DirectoryUtils.WriteUtf8FileAsync(fileName, json, cancellationToken);

						// Convert to ContentHistoryChangelistContentEntry
						var entry = ContentFileToContentHistoryChangelistContentEntry(contentFile, targetChangelist, changelistEntry);
						downloadedContent.Add(entry);
					}
					catch (Exception e)
					{
						Log.Error(e, $"Failed to save content history content for contentId={contentId}");
					}
				}
			}
			finally
			{
				_contentHistoryContentFileSystemSemaphore.Release();
			}
		}
		catch (OperationCanceledException)
		{
			Log.Debug($"{nameof(SyncContentHistoryContent)} was cancelled");
		}

		// Return a page containing the downloaded content files
		return new ContentHistoryContentPage() { ContentEntries = downloadedContent };
	}


	/// <summary>
	/// Converts a <see cref="ContentFile"/> to a <see cref="ContentHistoryChangelistContentEntry"/>.
	/// This is a simplified version of <see cref="LocalContentManifestEntry"/> that excludes fields dependent on ReferenceContent (like IsInConflict),
	/// which are not semantically appropriate in the content history.
	/// Uses the changelist entry to determine content status and populate old/new hashes and tags.
	/// </summary>
	public static ContentHistoryChangelistContentEntry ContentFileToContentHistoryChangelistContentEntry(
		ContentFile file,
		ContentHistoryChangelist changelist,
		ContentHistoryChangelistEntry changelistEntry)
	{
		// Determine status based on which dictionary this entry is in
		var status = ContentStatus.UpToDate;
		if (changelist.Created != null && changelist.Created.ContainsKey(file.Id))
		{
			status = ContentStatus.Created;
		}
		else if (changelist.Removed != null && changelist.Removed.ContainsKey(file.Id))
		{
			status = ContentStatus.Deleted;
		}
		else if (changelist.Modified != null && changelist.Modified.ContainsKey(file.Id))
		{
			status = ContentStatus.Modified;
		}

		// Compute tag status using old and new tags from the changelist entry
		var oldTags = changelistEntry.OldTags ?? Array.Empty<string>();
		var newTags = changelistEntry.NewTags ?? Array.Empty<string>();

		var oldTagsSet = new HashSet<string>(oldTags);
		var newTagsSet = new HashSet<string>(newTags);

		// Build a dictionary to look up tag status
		var tagStatusDict = new Dictionary<string, TagStatus>();
		foreach (var tag in newTags)
		{
			if (oldTagsSet.Contains(tag))
			{
				tagStatusDict[tag] = TagStatus.LocalAndRemote; // Tag exists in both old and new
			}
			else
			{
				tagStatusDict[tag] = TagStatus.LocalOnly; // Tag was added in new version
			}
		}

		foreach (var tag in oldTags)
		{
			if (!newTagsSet.Contains(tag))
			{
				tagStatusDict[tag] = TagStatus.RemoteOnly; // Tag was removed in new version
			}
		}

		// Compute TagsStatus array corresponding to NewTags
		var tagsStatus = newTags.Select(tag => (int)tagStatusDict[tag]).ToArray();

		return new ContentHistoryChangelistContentEntry()
		{
			FullId = file.Id,
			TypeName = GetContentType(file),
			Name = GetContentName(file),
			ChangeStatus = (int)status,
			NewHash = changelistEntry.NewChecksum ?? "",
			OldHash = changelistEntry.OldChecksum ?? "",
			NewTags = newTags,
			OldTags = oldTags,
			TagsStatus = tagsStatus,
			JsonFilePath = file.LocalFilePath,
			ReferenceManifestUid = file.FetchedFromManifestUid,
			ChangeDate = changelist.PublishedAt,
		};
	}

	/// <summary>
	/// Constructs the URL for downloading a content history changelist JSON file from the Beamable CDN.
	/// </summary>
	/// <param name="cid">The customer ID (CID)</param>
	/// <param name="pid">The realm id (PID)</param>
	/// <param name="entry">The content history entry containing the ManifestUid</param>
	/// <returns>The full HTTPS URL to the changelist JSON file on dev-content.beamable.com</returns>
	/// <remarks>
	/// URL format: https://dev-content.beamable.com/{cid}/{pid}/public/manifest-diffs/{manifestUid}.json
	/// No validation is performed on input parameters; assumes they are non-null and valid.
	/// </remarks>
	public static string GetContentHistoryChangelistUrl(string cid, string pid, ContentHistoryEntry entry)
	{
		return $"https://dev-content.beamable.com/{cid}/{pid}/public/manifest-diffs/{entry.ManifestUid}.json";
	}

	/// <summary>
	/// Constructs the URL for downloading a content history changelist JSON file from the Beamable CDN.
	/// Convenience overload that accepts a ManifestDiffSummary instead of a ContentHistoryEntry.
	/// </summary>
	/// <param name="cid">The customer ID (CID)</param>
	/// <param name="pid">The realm id (PID)</param>
	/// <param name="summary">The manifest diff summary to convert to a ContentHistoryEntry</param>
	/// <returns>The full HTTPS URL to the changelist JSON file on dev-content.beamable.com</returns>
	/// <remarks>
	/// Delegates to GetContentHistoryChangelistUrl(cid, pid, entry) after converting the summary.
	/// </remarks>
	public static string GetContentHistoryChangelistUrl(string cid, string pid, ManifestDiffSummary summary)
	{
		return GetContentHistoryChangelistUrl(cid, pid, ContentHistoryEntry.FromManifestDiff(summary));
	}

	/// <summary>
	/// Constructs the URL for downloading the new version of a content file from the Beamable CDN.
	/// </summary>
	/// <param name="cid">The customer ID (CID)</param>
	/// <param name="rootPid">The root realm id</param>
	/// <param name="contentId">The full content ID (e.g., "items.MyItem")</param>
	/// <param name="changelistEntry">The changelist entry containing the NewChecksum</param>
	/// <returns>The full HTTPS URL to the new content version JSON file on dev-content.beamable.com</returns>
	/// <remarks>
	/// URL format: https://dev-content.beamable.com/{cid}/{rootPid}/public/{contentId}/{newChecksum}.json
	/// No validation is performed; assumes changelistEntry.NewChecksum is non-null and valid.
	/// </remarks>
	public static string GetContentHistoryContentNewUrl(string cid, string rootPid, string contentId, ContentHistoryChangelistEntry changelistEntry)
	{
		return $"https://dev-content.beamable.com/{cid}/{rootPid}/public/{contentId}/{changelistEntry.NewChecksum}.json";
	}

	/// <summary>
	/// Constructs the URL for downloading the old version of a content file from the Beamable CDN.
	/// </summary>
	/// <param name="cid">The customer ID (CID)</param>
	/// <param name="rootPid">The root realm id</param>
	/// <param name="contentId">The full content ID (e.g., "items.MyItem")</param>
	/// <param name="changelistEntry">The changelist entry containing the OldChecksum</param>
	/// <returns>The full HTTPS URL to the old content version JSON file on dev-content.beamable.com</returns>
	/// <remarks>
	/// URL format: https://dev-content.beamable.com/{cid}/{rootPid}/public/{contentId}/{oldChecksum}.json
	/// No validation is performed; assumes changelistEntry.OldChecksum is non-null and valid.
	/// </remarks>
	public static string GetContentHistoryContentOldUrl(string cid, string rootPid, string contentId, ContentHistoryChangelistEntry changelistEntry)
	{
		return $"https://dev-content.beamable.com/{cid}/{rootPid}/public/{contentId}/{changelistEntry.OldChecksum}.json";
	}

	/// <summary>
	/// Searches for a content history entry within a page by manifest UID.
	/// </summary>
	/// <param name="inPage">The page of entries to search through</param>
	/// <param name="uid">The manifest UID to find</param>
	/// <returns>The matching ContentHistoryEntry, or default(ContentHistoryEntry) if not found</returns>
	/// <remarks>
	/// Edge cases:
	/// - Returns default struct value if no match is found
	/// - Performs linear search (O(n) complexity)
	/// - Assumes ManifestUid is unique within the page (returns first match)
	/// - Does not handle null inPage or null Entries list (will throw NullReferenceException)
	/// </remarks>
	public ContentHistoryEntry GetContentHistoryEntry(ContentHistoryEntriesPage inPage, string uid)
	{
		foreach (var e in inPage.Entries)
		{
			if (e.ManifestUid == uid)
				return e;
		}

		return default;
	}

	/// <summary>
	/// Searches for a content history entry within a page by creation date (Unix timestamp).
	/// Uses binary search since entries are guaranteed to be sorted by CreatedDate in descending order (most recent first).
	/// </summary>
	/// <param name="inPage">The page of entries to search through</param>
	/// <param name="unixTimestamp">The Unix timestamp (milliseconds) of the entry to find</param>
	/// <returns>The matching ContentHistoryEntry, or default(ContentHistoryEntry) if not found</returns>
	/// <remarks>
	/// Edge cases:
	/// - Returns default struct value if no match is found
	/// - Performs binary search (O(log n) complexity)
	/// - Assumes CreatedDate is unique within the page (though collisions are theoretically possible)
	/// - Assumes entries are sorted by CreatedDate in descending order (newest first, oldest last)
	/// - Does not handle null inPage or null Entries list (will throw NullReferenceException)
	/// - Returns default if Entries list is empty
	/// </remarks>
	public ContentHistoryEntry GetContentHistoryEntry(ContentHistoryEntriesPage inPage, long unixTimestamp)
	{
		if (inPage.Entries == null || inPage.Entries.Count == 0)
			return default;

		int left = 0;
		int right = inPage.Entries.Count - 1;

		while (left <= right)
		{
			int mid = left + (right - left) / 2;
			var midEntry = inPage.Entries[mid];

			if (midEntry.CreatedDate == unixTimestamp)
				return midEntry;

			// Descending order: if mid is greater than target, search right half
			if (midEntry.CreatedDate > unixTimestamp)
				left = mid + 1;
			else
				right = mid - 1;
		}

		return default;
	}

	/// <summary>
	/// Loads and deserializes a single content file from disk asynchronously.
	/// Retries reads in a busy-wait loop to avoid collisions with other processes modifying the file.
	/// Extracts the content ID from the filename and populates ContentFile.Id and LocalFilePath.
	/// </summary>
	/// <param name="fp">The full file path to the content JSON file</param>
	/// <returns>A tuple containing the content ID and the deserialized ContentFile</returns>
	/// <remarks>
	/// Edge cases:
	/// - Retries file reads in an infinite loop until successful or text is non-empty (busy-wait on IOException)
	/// - Content ID is derived from filename without extension (e.g., "items.MyItem.json" → "items.MyItem")
	/// - Throws and logs error if deserialization fails
	/// - Does not handle null or invalid file paths (will throw ArgumentException)
	/// - LocalFilePath is set to the full absolute path provided in fp parameter
	/// </remarks>
	private async Task<(string contentId, ContentFile file)> LoadContentFileAsync(string fp)
	{
		// We got to do this so that we don't collide with other software editing the files on disk.
		var text = "";
		var readText = false;
		while (!readText || text == "")
		{
			try
			{
				text = await File.ReadAllTextAsync(fp);
				readText = true;
			}
			catch (IOException)
			{
				readText = false;
				text = "";
			}
		}

		try
		{
			var contentId = Path.GetFileNameWithoutExtension(fp);
			var contentFile = JsonSerializer.Deserialize<ContentFile>(text, GetContentFileSerializationOptions());
			contentFile.Id = contentId;
			contentFile.LocalFilePath = fp;
			return (contentId, contentFile);
		}
		catch (Exception e)
		{
			Log.Error(e, $"Error when loading content history content file {fp}");
			throw;
		}
	}
}

public class ContentHistoryEntriesPage
{
	public string[] ContainedManifestUids;
	public long StartDate;
	public long EndDate;

	public List<ContentHistoryEntry> Entries;
}

[CliContractType, Serializable]
public struct ContentHistoryEntry : IEquatable<ContentHistoryEntry>
{
	public const string JSON_PROP_MANIFEST_UID = "manifestUid";
	public const string JSON_PROP_CREATED_DATE = "createdDate";
	public const string JSON_PROP_PUBLISHED_BY = "publishedBy";
	public const string JSON_PROP_PUBLISHED_BY_NAME = "publishedByName";
	public const string JSON_PROP_AFFECTED_CONTENT_IDS = "affectedContentIds";

	[JsonPropertyName(JSON_PROP_MANIFEST_UID)] [JsonProperty(JSON_PROP_MANIFEST_UID)]
	public string ManifestUid;

	[JsonPropertyName(JSON_PROP_CREATED_DATE)] [JsonProperty(JSON_PROP_CREATED_DATE)]
	public long CreatedDate;

	[JsonPropertyName(JSON_PROP_PUBLISHED_BY)] [JsonProperty(JSON_PROP_PUBLISHED_BY)]
	public string PublishedBy;

	[JsonPropertyName(JSON_PROP_PUBLISHED_BY_NAME)] [JsonProperty(JSON_PROP_PUBLISHED_BY_NAME)]
	public string PublishedByName;

	[JsonPropertyName(JSON_PROP_AFFECTED_CONTENT_IDS)] [JsonProperty(JSON_PROP_AFFECTED_CONTENT_IDS)]
	public string[] AffectedContentIds;

	public static ContentHistoryEntry FromManifestDiff(ManifestDiffSummary summary)
	{
		return new ContentHistoryEntry
		{
			ManifestUid = summary.manifestUid,
			CreatedDate = summary.createdDate,
			AffectedContentIds = summary.affectedContentIds ?? Array.Empty<string>(),
			PublishedBy = summary.publishedBy.GetOrElse(""),
			PublishedByName = summary.publishedByName.GetOrElse("")
		};
	}

	public bool Equals(ContentHistoryEntry other) => ManifestUid == other.ManifestUid;
	public override bool Equals(object obj) => obj is ContentHistoryEntry other && Equals(other);
	public override int GetHashCode() => (ManifestUid != null ? ManifestUid.GetHashCode() : 0);
	public static bool operator ==(ContentHistoryEntry left, ContentHistoryEntry right) => left.Equals(right);
	public static bool operator !=(ContentHistoryEntry left, ContentHistoryEntry right) => !left.Equals(right);
}

public class ContentHistoryFetchReport
{
	public List<ContentHistoryEntry> Entries;
}

public class LocalContentHistoryEntryFileChanges
{
	public List<ChangedContentHistoryEntryFile> AllFileChanges;
}

public struct ChangedContentHistoryEntryFile
{
	public const char ENTRY_FILE_NAME_SEPARATOR = '¬';

	public string OwnerPid;
	public string OwnerManifestId;

	public long OldUnixTimestamp;
	public long UnixTimestamp;

	public string ManifestUid;
	public string OldManifestUid;

	public string FullFilePath;
	public string OldFullFilePath;

	public bool WasDeleted() => string.IsNullOrEmpty(FullFilePath) && !string.IsNullOrEmpty(OldFullFilePath);
	public bool WasCreated() => !string.IsNullOrEmpty(FullFilePath) && string.IsNullOrEmpty(OldFullFilePath);
	public bool WasRenamed() => !WasDeleted() && !WasCreated() && FullFilePath != OldFullFilePath;
	public bool WasChanged() => !WasCreated() && !WasDeleted() && FullFilePath == OldFullFilePath;

	/// <summary>
	/// Parses a file name (without extension) of the form "createdDate¬manifestUid" into its parts.
	/// </summary>
	public static bool TryParseEntryFileName(string fileNameWithoutExtension, out long createdDate, out string manifestUid)
	{
		createdDate = 0;
		manifestUid = "";
		if (string.IsNullOrEmpty(fileNameWithoutExtension)) return false;

		var parts = fileNameWithoutExtension.Split(ENTRY_FILE_NAME_SEPARATOR);
		if (parts.Length != 2) return false;
		if (!long.TryParse(parts[0], out createdDate)) return false;
		manifestUid = parts[1];
		return true;
	}

	/// <summary>
	/// Builds the file name (without extension) from a createdDate and manifestUid.
	/// </summary>
	public static string BuildEntryFileName(long createdDate, string manifestUid) => $"{createdDate}{ENTRY_FILE_NAME_SEPARATOR}{manifestUid}";
}

public class LocalContentHistoryChangelistFileChanges
{
	public List<ChangedContentHistoryChangelistFile> AllFileChanges;
}

public struct ChangedContentHistoryChangelistFile
{
	public string OwnerPid;
	public string OwnerManifestId;

	public string OldManifestUid;
	public string ManifestUid;

	public string FullFilePath;
	public string OldFullFilePath;

	public bool WasReadAccessed;

	public bool WasDeleted() => string.IsNullOrEmpty(FullFilePath) && !string.IsNullOrEmpty(OldFullFilePath);
	public bool WasCreated() => !string.IsNullOrEmpty(FullFilePath) && string.IsNullOrEmpty(OldFullFilePath);
	public bool WasRenamed() => !WasDeleted() && !WasCreated() && FullFilePath != OldFullFilePath;
	public bool WasChanged() => !WasCreated() && !WasDeleted() && FullFilePath == OldFullFilePath && !WasReadAccessed;
	public bool WasRead() => !WasCreated() && !WasDeleted() && FullFilePath == OldFullFilePath && WasReadAccessed;
}

public class ContentHistoryChangelistPage
{
	public ContentHistoryChangelist[] Changelists = Array.Empty<ContentHistoryChangelist>();
}

public class ContentHistoryContentPage
{
	public List<ContentHistoryChangelistContentEntry> ContentEntries = new();
}

/// <summary>
/// Here's an example JSON of this structure. It contains a diff between two published content manifests.
/// 
/// {
///   "manifestUid": "64f1a2b3c4d5e6f7a8b9c0d1",
///   "previousManifestUid": "64f1a2b3c4d5e6f7a8b9c0d0",
///   "publishedBy": "pedro@beamable.com",
///   "publishedAt": 1640995800000,
///
///   "deleted": {
///     "content.item3": {
///       "oldVersion": "1",
///       "oldChecksum": "jkl012",
///       "oldUri": "https://content.beamable.com/item3/1.json",
///       "oldTags": ["deprecated"]
///     },
///     "content.level1": {
///       "oldVersion": "7",
///       "oldChecksum": "mno345",
///       "oldUri": "https://content.beamable.com/level1/7.json",
///       "oldTags": ["beta"]
///     },
///     "content.skin.classic": {
///       "oldVersion": "3",
///       "oldChecksum": "pqr678",
///       "oldUri": "https://content.beamable.com/skin/classic/3.json",
///       "oldTags": ["legacy", "skin"]
///     }
///   },
///
///   "modified": {
///     "content.item1": {
///       "oldVersion": "1",
///       "newVersion": "2",
///       "oldChecksum": "abc123",
///       "newChecksum": "def456",
///       "oldUri": "https://content.beamable.com/item1/1.json",
///       "newUri": "https://content.beamable.com/item1/2.json",
///       "oldTags": ["base"],
///       "newTags": ["base", "updated"]
///     },
///     "content.quest.daily": {
///       "oldVersion": "5",
///       "newVersion": "6",
///       "oldChecksum": "stu901",
///       "newChecksum": "vwx234",
///       "oldUri": "https://content.beamable.com/quest/daily/5.json",
///       "newUri": "https://content.beamable.com/quest/daily/6.json",
///       "oldTags": ["daily"],
///       "newTags": ["daily", "tuned"]
///     },
///     "content.bundle.starter": {
///       "oldVersion": "2",
///       "newVersion": "3",
///       "oldChecksum": "yz0123",
///       "newChecksum": "abc456",
///       "oldUri": "https://content.beamable.com/bundle/starter/2.json",
///       "newUri": "https://content.beamable.com/bundle/starter/3.json",
///       "oldTags": ["promo"],
///       "newTags": ["promo", "discounted"]
///     }
///   },
///
///   "created": {
///     "content.item2": {
///       "version": "1",
///       "checksum": "ghi789",
///       "uri": "https://content.beamable.com/item2/1.json",
///       "tags": ["new"]
///     },
///     "content.event.holiday": {
///       "version": "1",
///       "checksum": "def789",
///       "uri": "https://content.beamable.com/event/holiday/1.json",
///       "tags": ["seasonal", "holiday"]
///     },
///     "content.skin.neo": {
///       "version": "1",
///       "checksum": "ghi012",
///       "uri": "https://content.beamable.com/skin/neo/1.json",
///       "tags": ["skin", "premium"]
///     }
///   }
/// }{
///   "manifestUid": "64f1a2b3c4d5e6f7a8b9c0d1",
///   "previousManifestUid": "64f1a2b3c4d5e6f7a8b9c0d0",
///   "publishedBy": "pedro@beamable.com",
///   "publishedAt": 1640995800000,
///
///   "deleted": {
///     "content.item3": {
///       "oldVersion": "1",
///       "oldChecksum": "jkl012",
///       "oldUri": "https://content.beamable.com/item3/1.json",
///       "oldTags": ["deprecated"]
///     },
///     "content.level1": {
///       "oldVersion": "7",
///       "oldChecksum": "mno345",
///       "oldUri": "https://content.beamable.com/level1/7.json",
///       "oldTags": ["beta"]
///     },
///     "content.skin.classic": {
///       "oldVersion": "3",
///       "oldChecksum": "pqr678",
///       "oldUri": "https://content.beamable.com/skin/classic/3.json",
///       "oldTags": ["legacy", "skin"]
///     }
///   },
///
///   "modified": {
///     "content.item1": {
///       "oldVersion": "1",
///       "newVersion": "2",
///       "oldChecksum": "abc123",
///       "newChecksum": "def456",
///       "oldUri": "https://content.beamable.com/item1/1.json",
///       "newUri": "https://content.beamable.com/item1/2.json",
///       "oldTags": ["base"],
///       "newTags": ["base", "updated"]
///     },
///     "content.quest.daily": {
///       "oldVersion": "5",
///       "newVersion": "6",
///       "oldChecksum": "stu901",
///       "newChecksum": "vwx234",
///       "oldUri": "https://content.beamable.com/quest/daily/5.json",
///       "newUri": "https://content.beamable.com/quest/daily/6.json",
///       "oldTags": ["daily"],
///       "newTags": ["daily", "tuned"]
///     },
///     "content.bundle.starter": {
///       "oldVersion": "2",
///       "newVersion": "3",
///       "oldChecksum": "yz0123",
///       "newChecksum": "abc456",
///       "oldUri": "https://content.beamable.com/bundle/starter/2.json",
///       "newUri": "https://content.beamable.com/bundle/starter/3.json",
///       "oldTags": ["promo"],
///       "newTags": ["promo", "discounted"]
///     }
///   },
///
///   "created": {
///     "content.item2": {
///       "version": "1",
///       "checksum": "ghi789",
///       "uri": "https://content.beamable.com/item2/1.json",
///       "tags": ["new"]
///     },
///     "content.event.holiday": {
///       "version": "1",
///       "checksum": "def789",
///       "uri": "https://content.beamable.com/event/holiday/1.json",
///       "tags": ["seasonal", "holiday"]
///     },
///     "content.skin.neo": {
///       "version": "1",
///       "checksum": "ghi012",
///       "uri": "https://content.beamable.com/skin/neo/1.json",
///       "tags": ["skin", "premium"]
///     }
///   }
/// }
/// </summary>
[CliContractType, Serializable]
public struct ContentHistoryChangelist
{
	[JsonPropertyName("manifestUid")] [JsonProperty("manifestUid")]
	public string ManifestUid;

	[JsonPropertyName("previousManifestUid")] [JsonProperty("previousManifestUid")]
	public string PreviousManifestUid;

	[JsonPropertyName("publishedBy")] [JsonProperty("publishedBy")]
	public string PublishedBy;

	[JsonPropertyName("publishedAt")] [JsonProperty("publishedAt")]
	public long PublishedAt;

	[JsonPropertyName("created")] [JsonProperty("created")]
	public Dictionary<string, ContentHistoryChangelistEntry> Created;

	[JsonPropertyName("removed")] [JsonProperty("removed")]
	public Dictionary<string, ContentHistoryChangelistEntry> Removed;

	[JsonPropertyName("modified")] [JsonProperty("modified")]
	public Dictionary<string, ContentHistoryChangelistEntry> Modified;
}

/// <summary>
/// This structure deserializes the following Changelist Entry JSON:
///
/// {
///   "oldVersion": "2246bce31494153606f6ef3132923cd50cd82fdc",
///   "oldChecksum": "86b656f5768bb357de3e259d624cf8a315021f15",
///   "oldTags": ["asd", "asdasd"],
///   "newVersion": "2246bce31494153606f6ef3132923cd50cd82fdc",
///   "newChecksum": "86b656f5768bb357de3e259d624cf8a315021f15",
///   "newTags": ["asd", "asdasd"]
/// }
///
/// </summary>
public struct ContentHistoryChangelistEntry
{
	[JsonPropertyName("oldVersion")] [JsonProperty("oldVersion")]
	public string OldVersion;

	[JsonPropertyName("oldChecksum")] [JsonProperty("oldChecksum")]
	public string OldChecksum;

	[JsonPropertyName("oldTags")] [JsonProperty("oldTags")]
	public string[] OldTags;

	[JsonPropertyName("newVersion")] [JsonProperty("newVersion")]
	public string NewVersion;

	[JsonPropertyName("newChecksum")] [JsonProperty("newChecksum")]
	public string NewChecksum;

	[JsonPropertyName("newTags")] [JsonProperty("newTags")]
	public string[] NewTags;

	/// <summary>
	/// The local file path where this content is expected to be stored.
	/// This is computed during sync and is not part of the JSON response.
	/// Format: {ContentHistoryContentPath}/{pid}/{manifestId}/{manifestUid}/{contentId}.json
	/// </summary>
	[JsonPropertyName("jsonFilePath")] [JsonProperty("jsonFilePath")]
	public string JsonFilePath;

	/// <summary>
	/// The full content id string (e.g., "items.MyItem").
	/// This is computed during sync and is not part of the JSON response.
	/// </summary>
	[JsonPropertyName("fullId")] [JsonProperty("fullId")]
	public string FullId;

	/// <summary>
	/// The type part of the content ID (e.g., "items" from "items.MyItem").
	/// This is computed during sync and is not part of the JSON response.
	/// </summary>
	[JsonPropertyName("typeName")] [JsonProperty("typeName")]
	public string TypeName;

	/// <summary>
	/// The name part of the content ID (e.g., "MyItem" from "items.MyItem").
	/// This is computed during sync and is not part of the JSON response.
	/// </summary>
	[JsonPropertyName("name")] [JsonProperty("name")]
	public string Name;

	/// <summary>
	/// Int value of <see cref="ContentStatus"/> for this entry.
	/// Indicates whether the content was Created, Modified, or Deleted in this changelist.
	/// This is computed during sync and is not part of the JSON response.
	/// </summary>
	[JsonPropertyName("changeStatus")] [JsonProperty("changeStatus")]
	public int ChangeStatus;

	/// <summary>
	/// The time that this content change was published (Unix timestamp in milliseconds).
	/// This is computed during sync and is not part of the JSON response.
	/// </summary>
	[JsonPropertyName("changeDate")] [JsonProperty("changeDate")]
	public long ChangeDate;
}

/// <summary>
/// Simplified version of <see cref="LocalContentManifestEntry"/> used for content history changesets.
/// Does not include fields that depend on ReferenceContent like IsInConflict, as these cannot be correctly
/// computed during ContentFile usage inside ContentService.History.cs and ContentHistoryCommand.cs.
/// </summary>
[CliContractType, Serializable]
public struct ContentHistoryChangelistContentEntry
{
	/// <summary>
	/// The full content id string.
	/// </summary>
	public string FullId;

	/// <summary>
	/// The type part of the <see cref="FullId"/>.
	/// </summary>
	public string TypeName;

	/// <summary>
	/// The name part of the <see cref="FullId"/>
	/// </summary>
	public string Name;

	/// <summary>
	/// Int value of <see cref="ContentStatus"/> for this entry.
	/// Indicates whether the content was Created, Modified, or Deleted in this changelist.
	/// </summary>
	public int ChangeStatus;

	/// <summary>
	/// The MD5 hash of the new version of the content properties.
	/// See <see cref="ContentService.CalculateChecksum(in Constants.Features.Content.ContentFile)"/>.
	/// </summary>
	public string NewHash;

	/// <summary>
	/// The MD5 hash of the old version of the content properties.
	/// Empty for newly created content.
	/// </summary>
	public string OldHash;

	/// <summary>
	/// The tags of the new version of this content.
	/// </summary>
	public string[] NewTags;

	/// <summary>
	/// The tags of the old version of this content.
	/// Empty for newly created content.
	/// </summary>
	public string[] OldTags;

	/// <summary>
	/// The array of <see cref="TagStatus"/> values corresponding to NewTags.
	/// Each element indicates whether the tag was added, removed, or unchanged.
	/// </summary>
	public int[] TagsStatus;

	/// <summary>
	/// The path to the local <see cref="ContentFile"/>.
	/// This is empty when the file is deleted locally.
	/// </summary>
	public string JsonFilePath;

	/// <summary>
	/// ID of the last published manifest to which this content was ever sync'ed.
	/// </summary>
	public string ReferenceManifestUid;

	/// <summary>
	/// The time that this content change was published (Unix timestamp in milliseconds)
	/// </summary>
	public long ChangeDate;

	/// <summary>
	/// This is done this way because Unreal can't generate the enums properly but... unity can use this type directly.
	/// So... we declare this as a helper.
	/// </summary>
	public ContentStatus StatusEnum => (ContentStatus)ChangeStatus;
}

public partial class ContentService
{
	/// <summary>
	/// Restores local content files from content history, overwriting them with the version stored in the specified manifest UID.
	/// If content is not locally cached in history, it will be automatically downloaded.
	/// The referenceManifestId of the local content file will be preserved (not replaced with the one from history).
	/// </summary>
	/// <param name="manifestUid">The manifest UID from history to restore content from</param>
	/// <param name="contentIds">Optional collection of content IDs to restore; if null or empty, all content in the manifest UID will be restored</param>
	/// <param name="manifestId">The manifest ID, defaults to "global"</param>
	/// <param name="cancellationToken">Cancellation token to abort the restore operation</param>
	/// <returns>A list of content IDs that were successfully restored</returns>
	/// <remarks>
	/// This function:
	/// 1. Loads the changelist for the specified manifestUid to determine which content exists in that version
	/// 2. Ensures all required history content files are downloaded (calls SyncContentHistoryContent if needed)
	/// 3. For each content file, reads it from the history folder
	/// 4. Reads the current local content file to get the original referenceManifestId
	/// 5. Overwrites the local content file with the history version, preserving the original referenceManifestId
	/// 6. Uses the file system semaphore to prevent race conditions with other content operations
	/// </remarks>
	public async Task<List<string>> RestoreContentFromHistory(string manifestUid, IEnumerable<string> contentIds = null, string manifestId = "global", CancellationToken cancellationToken = default)
	{
		var pid = _requester.Pid;
		var restoredContentIds = new List<string>();

		// Fetch the latest manifest to use as fallback for referenceManifestId
		var latestManifestPromise = GetManifest(manifestId);

		// Load the changelist for this manifestUid to determine what content exists
		var changelists = await GetAllContentHistoryLocalChangelists(pid, manifestId, new[] { manifestUid });
		if (changelists.Changelists == null || changelists.Changelists.Length == 0)
		{
			throw new CliException($"No changelist found for manifest UID: {manifestUid}");
		}

		var changelist = changelists.Changelists[0];
		var latestManifest = await latestManifestPromise;

		// Determine which content IDs we need to restore
		var allContentInChangelist = new HashSet<string>();
		if (changelist.Created != null) allContentInChangelist.UnionWith(changelist.Created.Keys);
		if (changelist.Modified != null) allContentInChangelist.UnionWith(changelist.Modified.Keys);
		if (changelist.Removed != null) allContentInChangelist.UnionWith(changelist.Removed.Keys);

		// Filter to requested content IDs if specified
		var targetContentIds = contentIds != null && contentIds.Any()
			? allContentInChangelist.Intersect(contentIds).ToList()
			: allContentInChangelist.ToList();

		if (targetContentIds.Count == 0)
		{
			return restoredContentIds; // Nothing to restore
		}

		// Ensure all history content files are downloaded
		await SyncContentHistoryContent(pid, manifestId, manifestUid, targetContentIds, cancellationToken);

		// Get the path to the history content folder for this manifest UID
		var historyContentPath = Path.Combine(ContentHistoryContentPath, pid, manifestId, manifestUid);

		// Get the path to the local content folder
		var localContentFolder = EnsureContentPathForRealmExists(out _, pid, manifestId);

		// Acquire the file system semaphore to prevent race conditions
		await _fileSystemOperationSemaphore.WaitAsync(cancellationToken);
		try
		{
			foreach (var contentId in targetContentIds)
			{
				try
				{
					// Read the history content file
					var historyFilePath = Path.Combine(historyContentPath, $"{contentId}.json");
					if (!File.Exists(historyFilePath))
					{
						Log.Warning($"History content file not found for {contentId} in manifest {manifestUid}");
						continue;
					}

					var historyJsonText = await File.ReadAllTextAsync(historyFilePath, cancellationToken);
					var historyJson = JsonSerializer.Deserialize<JsonElement>(historyJsonText, GetContentFileSerializationOptions());

					// Read the current local content file to get the original referenceManifestId
					var localFilePath = Path.Combine(localContentFolder, $"{contentId}.json");
					string originalReferenceManifestId = null;

					if (File.Exists(localFilePath))
					{
						var localJsonText = await File.ReadAllTextAsync(localFilePath, cancellationToken);
						var localJson = JsonSerializer.Deserialize<JsonElement>(localJsonText, GetContentFileSerializationOptions());

						// Extract the original referenceManifestId
						if (localJson.TryGetProperty(ContentFile.JSON_NAME_REFERENCE_MANIFEST_ID, out var refManifestIdElement))
						{
							originalReferenceManifestId = refManifestIdElement.GetString();
						}
					}

					// If we don't have an original reference, use the latest published manifest uid
					originalReferenceManifestId ??= latestManifest.uid.GetOrElse(manifestUid);

					// Create a new JSON object with the history content but preserving the original referenceManifestId
					var properties = historyJson.GetProperty(ContentFile.JSON_NAME_PROPERTIES);
					var tags = historyJson.GetProperty(ContentFile.JSON_NAME_TAGS);

					var restoredContentFile = new ContentFile
					{
						Id = contentId,
						Properties = properties,
						Tags = tags,
						FetchedFromManifestUid = originalReferenceManifestId
					};

					// Save the restored content file to the local content folder
					await SaveContentFile(localContentFolder, restoredContentFile, cancellationToken);

					restoredContentIds.Add(contentId);
					Log.Information($"Restored content {contentId} from history manifest {manifestUid}");
				}
				catch (Exception e)
				{
					Log.Error(e, $"Failed to restore content {contentId} from history");
				}
			}
		}
		finally
		{
			_fileSystemOperationSemaphore.Release();
		}

		return restoredContentIds;
	}
}
