using Beamable.Api.Autogenerated.Beamobundle;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common.BeamCli.Contracts;
using Beamable.Server;
using cli.Services.Bundles;
using Spectre.Console;
using System;
using System.Collections.Generic;
using System.CommandLine;
using System.Linq;

namespace cli.BundleCommands;

public class BundleReleasesCommandArgs : CommandArgs
{
	public string bundleName;
	public int limit;
}

public class BundleReleasesCommandOutput
{
	/// <summary>The bundle's releases, newest first.</summary>
	public BundleReleaseInfo[] releases = Array.Empty<BundleReleaseInfo>();

	/// <summary>The bundle's tags, including @latest. A tag points at a checksum, not a version.</summary>
	public BundleTagInfo[] tags = Array.Empty<BundleTagInfo>();
}

/// <summary>
/// Show a bundle's release log. The endpoint is paged on an exclusive version cursor, so this
/// walks it to the end rather than showing a first page as if it were the whole log.
/// </summary>
public class BundleReleasesCommand
	: AtomicCommand<BundleReleasesCommandArgs, BundleReleasesCommandOutput>, ISkipManifest
{
	/// <summary>The endpoint's own maximum page size.</summary>
	private const int PageSize = 200;

	public BundleReleasesCommand() : base("releases", "Show the release log for a bundle")
	{
	}

	public override void Configure()
	{
		AddArgument(new Argument<string>("bundle-name", "The bundle name, optionally namespaced as @<namespace>/<bundle-name>"),
			(args, i) => args.bundleName = i);
		AddOption(new Option<int>("--limit", () => 0, "Stop after this many releases, newest first. 0 (the default) walks the whole log"),
			(args, i) => args.limit = i);
	}

	public override async Task<BundleReleasesCommandOutput> GetResult(BundleReleasesCommandArgs args)
	{
		var api = args.Provider.GetService<IBeamBeamobundleApi>();
		var (explicitNs, name) = BundleNamespace.SplitName(args.bundleName);
		BundleWorkspace.ValidateName(name);
		var ns = await BundleNamespace.Resolve(args, explicitNs);

		var releases = new List<BundleReleaseInfo>();
		var tags = Array.Empty<BundleTagInfo>();
		long? fromVersion = null;

		while (true)
		{
			var response = await api.GetBundlesReleases(name, ns, fromVersion, PageSize);
			tags = response.tags.ToTagInfos();

			var page = (response.releases ?? Array.Empty<BundleRelease>())
				.Select(BundleReleaseInfo.FromRelease)
				.ToArray();
			releases.AddRange(page);

			var reachedLimit = args.limit > 0 && releases.Count >= args.limit;
			if (page.Length < PageSize || reachedLimit)
				break;

			fromVersion = page[^1].version;
		}

		if (args.limit > 0 && releases.Count > args.limit)
			releases = releases.Take(args.limit).ToList();

		return new BundleReleasesCommandOutput { releases = releases.ToArray(), tags = tags };
	}

	protected override void LogResult(object result)
	{
		if (result is not BundleReleasesCommandOutput output)
		{
			base.LogResult(result);
			return;
		}

		// A tag points at a checksum, and a revert puts several versions on one checksum, so every
		// version holding a tagged checksum shows the tag.
		var tagsByChecksum = output.tags
			.GroupBy(t => t.checksum)
			.ToDictionary(g => g.Key, g => string.Join(", ", g.Select(t => t.tag)));

		var table = new Table();
		table.AddColumn("Version");
		table.AddColumn("Published At");
		table.AddColumn("Checksum");
		table.AddColumn("Tags");

		foreach (var release in output.releases)
		{
			table.AddRow(
				Markup.Escape(release.version.ToString()),
				Markup.Escape(BundleInfo.FormatPublishedAt(release.publishedAt)),
				Markup.Escape(release.checksum),
				Markup.Escape(tagsByChecksum.TryGetValue(release.checksum, out var t) ? t : "-"));
		}

		AnsiConsole.Write(table);
	}
}
