using Beamable.Api.Autogenerated.Beamobundle;
using Beamable.Api.Autogenerated.Models;
using Beamable.Server;
using cli.Services.Bundles;
using System.CommandLine;

namespace cli.BundleCommands;

public class BundleTagsCommandArgs : CommandArgs
{
	public string bundleName;
}

public class BundleTagsCommandOutput
{
	public BundleTag[] tags;
}

public class BundleTagsCommand : AtomicCommand<BundleTagsCommandArgs, BundleTagsCommandOutput>, ISkipManifest
{
	public BundleTagsCommand() : base("tags", "Show the tag to checksum mapping for a bundle")
	{
	}

	public override void Configure()
	{
		AddArgument(new Argument<string>("bundle-name", "The bundle name"),
			(args, i) => args.bundleName = i);
	}

	public override async Task<BundleTagsCommandOutput> GetResult(BundleTagsCommandArgs args)
	{
		var api = args.Provider.GetService<IBeamBeamobundleApi>();
		BundleWorkspace.ValidateName(args.bundleName);
		var ns = await BundleNamespace.Get(args);
		var response = await api.GetBundles(args.bundleName, ns);
		return new BundleTagsCommandOutput { tags = response.tags };
	}
}
