using System;
using System.Linq;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common.BeamCli.Contracts;
using Beamable.Common.Content;

namespace cli.BundleCommands;

/// <summary>
/// Maps a bundle's tags onto the <see cref="BundleTagInfo"/> contract. The mapping lives in the
/// CLI because the contract assembly copies (Unity/Unreal) don't ship the autogenerated API
/// models. The single-bundle endpoints return a tag-to-checksum map, the catalog list returns an
/// array of user tags, so both shapes map here.
/// </summary>
public static class BundleTagInfoExtensions
{
	public static BundleTagInfo[] ToTagInfos(this OptionalMapOfString tags)
	{
		var map = tags?.GetOrElse(new MapOfString()) ?? new MapOfString();
		return map
			.OrderBy(kvp => kvp.Key, StringComparer.Ordinal)
			.Select(kvp => new BundleTagInfo { tag = kvp.Key, checksum = kvp.Value })
			.ToArray();
	}

	public static BundleTagInfo[] ToTagInfos(this OptionalArrayOfBundleSummaryTag tags)
	{
		var array = tags?.GetOrElse(Array.Empty<BundleSummaryTag>()) ?? Array.Empty<BundleSummaryTag>();
		return array
			.Select(t => new BundleTagInfo
			{
				tag = t.tag.GetOrElse(""),
				checksum = t.checksum.GetOrElse(""),
			})
			.OrderBy(t => t.tag, StringComparer.Ordinal)
			.ToArray();
	}
}
