using Beamable.Api.Autogenerated.Beamobundle;
using Beamable.Api.Autogenerated.Models;
using Beamable.Server;
using cli.Services.Bundles;
using System.CommandLine;

namespace cli.BundleCommands;

public class BundleAclCommandArgs : CommandArgs
{
	public string bundleRef;
	public string scope;
}

public class BundleAclCommandOutput
{
	public string name;
	public string checksum;
	public string scope;
}

/// <summary>
/// Widen a bundle checksum's ACL. Admin-gated server-side.
/// NOTE: the generated client (<c>BeamBeamobundle.gs.cs</c>) issues an HTTP GET with a request body
/// to the <c>/acl</c> endpoint. If the backend expects PATCH this will fail at runtime — verify
/// against the host/OpenAPI source before relying on it (likely a generator/spec mismatch to fix).
/// </summary>
public class BundleAclCommand : AtomicCommand<BundleAclCommandArgs, BundleAclCommandOutput>, ISkipManifest
{
	public BundleAclCommand() : base("acl", "Widen the ACL scope on a bundle checksum")
	{
	}

	public override void Configure()
	{
		AddArgument(new Argument<string>("bundle-ref", "The bundle checksum reference, e.g. <namespace>/<bundle-name>@sha256:<checksum>"),
			(args, i) => args.bundleRef = i);
		AddOption(new Option<string>("--scope", "Visibility tier to widen to (each tier is a superset of the previous, not a list of realms): 'realm' = only this realm; 'org' = every realm in your customer; 'public' = every realm in every customer. A literal <cid>.<pid> / <cid> / * is also accepted"),
			(args, i) => args.scope = i);
	}

	public override async Task<BundleAclCommandOutput> GetResult(BundleAclCommandArgs args)
	{
		var api = args.Provider.GetService<IBeamBeamobundleApi>();
		var (fullName, checksum) = BundleRef.RequireChecksum(args.bundleRef);
		var (ns, name) = BundleWorkspace.SplitBundleName(fullName);
		var scope = BundleAclScope.Resolve(args.scope, args.AppContext);
		await api.PatchBundlesChecksumsAcl(name, checksum, ns, new UpdateBundleAclRequest { scope = scope });
		return new BundleAclCommandOutput { name = fullName, checksum = checksum, scope = scope };
	}
}
