using Beamable.Api.Autogenerated.Beamobundle;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common.Api;
using Beamable.Server;
using cli.Services;
using cli.Services.Bundles;
using Spectre.Console;
using System;
using System.Collections.Generic;
using System.Linq;

namespace cli.BundleCommands;

public class ListBundlesCommandArgs : CommandArgs
{
}

public class ListBundlesCommandOutput
{
	/// <summary>Published bundles in the catalog that are visible to the current realm.</summary>
	public BundleSummaryInfo[] published = Array.Empty<BundleSummaryInfo>();

	/// <summary>
	/// Bundles authored in this workspace (may not be published to the catalog yet). A different
	/// shape from <see cref="published"/>: the catalog list is per-name, so it has no component
	/// references, while a local bundle has nothing but them.
	/// </summary>
	public BundleInfo[] local = Array.Empty<BundleInfo>();
}

public class ListBundlesCommand : AtomicCommand<ListBundlesCommandArgs, ListBundlesCommandOutput>
{
	public ListBundlesCommand() : base("list", "List locally authored bundles and published bundles visible to the current realm")
	{
	}

	public override void Configure()
	{
	}

	public override async Task<ListBundlesCommandOutput> GetResult(ListBundlesCommandArgs args)
	{
		// The logical bundle name is always @<alias>/<bundle-name>, same as the published entries.
		// Resolved best-effort so the local list still works when the namespace can't be resolved.
		var ns = await BundleNamespace.TryGet(args);
		if (ns == null)
			Log.Warning("Could not resolve the bundle namespace (customer alias); showing local bundle names without it.");

		// Locally-authored bundles from the workspace (use Discover, not DiscoverAndValidate, so a
		// partition conflict doesn't prevent listing).
		var local = BundleWorkspace.Discover(args.ConfigService)
			.Select(b => FromLocalBundle(b, args.BeamoLocalSystem.BeamoManifest, ns))
			.ToArray();

		// Published catalog bundles. Tolerate a fetch failure (e.g. not logged in / no realm) so the
		// local list is still returned.
		BundleSummaryInfo[] published;
		try
		{
			var response = await args.Provider.GetService<IBeamBeamobundleApi>().GetBundles();
			published = (response.bundles ?? Array.Empty<BundleSummary>())
				.Select(BundleSummaryInfo.FromSummary).ToArray();
		}
		catch (RequesterException e)
		{
			Log.Warning($"Could not fetch published bundles from the catalog (status={e.Status}); showing local bundles only.");
			published = Array.Empty<BundleSummaryInfo>();
		}

		return new ListBundlesCommandOutput { published = published, local = local };
	}

	protected override void LogResult(object result)
	{
		if (result is not ListBundlesCommandOutput output)
		{
			base.LogResult(result);
			return;
		}

		var published = new Table().Title("Published");
		published.AddColumn("Name");
		published.AddColumn("Updated At");
		published.AddColumn("Version");
		published.AddColumn("Latest Checksum");
		published.AddColumn("ACL");
		published.AddColumn("Tags");
		foreach (var bundle in output.published)
		{
			published.AddRow(
				Markup.Escape(bundle.name),
				Markup.Escape(BundleInfo.FormatPublishedAt(bundle.updatedAt)),
				Markup.Escape(bundle.latestVersion.ToString()),
				Markup.Escape(bundle.latestChecksum),
				Markup.Escape(bundle.acl),
				Markup.Escape(bundle.FormatTags()));
		}
		AnsiConsole.Write(published);

		var local = new Table().Title("Local");
		local.AddColumn("Name");
		local.AddColumn("Path");
		foreach (var bundle in output.local)
		{
			local.AddRow(
				Markup.Escape(bundle.name),
				Markup.Escape(bundle.filePath));
		}
		AnsiConsole.Write(local);
	}

	/// <summary>
	/// Project an authored bundle config into the same shape as a published catalog entry. The
	/// authored config only lists flat beamoIds, so they are classified into services/storages/portal
	/// extensions using the local manifest.
	/// </summary>
	private static BundleInfo FromLocalBundle(BundleConfigFile bundle, BeamoLocalManifest localManifest, string ns)
	{
		var services = new List<string>();
		var storages = new List<string>();
		var extensions = new List<string>();
		foreach (var component in bundle.components)
		{
			var definition = localManifest.ServiceDefinitions.FirstOrDefault(d => d.BeamoId == component);
			switch (definition?.Protocol)
			{
				case BeamoProtocolType.HttpMicroservice:
					services.Add(component);
					break;
				case BeamoProtocolType.EmbeddedMongoDb:
					storages.Add(component);
					break;
				case BeamoProtocolType.PortalExtension:
					extensions.Add(component);
					break;
				default:
					Log.Warning($"Bundle=[{bundle.name}] lists component=[{component}] which is not a known local service/storage/extension.");
					break;
			}
		}

		return new BundleInfo
		{
			name = ns == null ? bundle.name : BundleNamespace.Qualify(ns, bundle.name),
			filePath = bundle.filePath,
			serviceNames = services.ToArray(),
			storageIds = storages.ToArray(),
			portalExtensionNames = extensions.ToArray(),
			bundleDependencies = bundle.bundleDependencies.ToDictionary(
				kvp => kvp.Key, kvp => kvp.Value?.Format() ?? ""),
		};
	}
}
