using Beamable.Api.Autogenerated.Beamobundle;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common.Content;
using Beamable.Server;
using cli.Commands.Project;
using cli.Deployment.Services;
using cli.DeploymentCommands;
using cli.Services;
using cli.Services.Bundles;
using Spectre.Console;
using System;
using System.Collections.Generic;
using System.CommandLine;
using System.Linq;

namespace cli.BundleCommands;

public class PublishBundleCommandArgs : CommandArgs, IHasDeployPlanArgs
{
	public string bundleName;
	public string tag;
	public string scope;
	public string fromPlanFile;
	public bool fromLastPlan;

	// IHasDeployPlanArgs (mirrors ReleaseDeploymentCommandArgs)
	public string Comment { get; set; }
	public string[] ServiceComments { get; set; }
	public string FromManifestFile { get; set; }
	public string ManifestId { get; set; }
	public bool UseLatestDeployedManifest { get; set; }
	public DeployMode DeployMode { get; set; }
	public bool RunHealthChecks { get; set; }
	public bool UseSequentialBuild { get; set; }
	public int MaxParallelTask { get; set; }
	public int MaxConcurrentUploads { get; set; }
	public string SlnFilePath;

	public string SolutionFilePath
	{
		get => SlnFilePath;
		set => SlnFilePath = value;
	}
}

public class PublishBundleCommandOutput
{
	public string name;
	public string checksum;
	public bool isNew;
	public BundleDiffResult diff;
}

public class PublishBundleCommand
	: AppCommand<PublishBundleCommandArgs>
	, IResultSteam<DefaultStreamResultChannel, PublishBundleCommandOutput>
	, IResultSteam<RunProjectBuildErrorStreamChannel, RunProjectBuildErrorStream>
	, IResultSteam<PlanReleaseProgressChannel, PlanReleaseProgress>
{
	public override bool AutoLogOutput => false;

	public PublishBundleCommand() : base("publish", "Build and publish an authored bundle to the catalog")
	{
	}

	public override void Configure()
	{
		DeployArgs.AddPlanOptions(this);
		SolutionCommandArgs.ConfigureSolutionFlag(this, _ => throw new CliException("Must have a valid .beamable folder"));
		AddArgument(new Argument<string>("bundle-name", "The bundle name to publish"),
			(args, i) => args.bundleName = i);
		AddOption(new Option<string>(new[] { "--from-plan", "--plan", "-p" }, "The file path to a pre-generated bundle plan file using the `bundles plan` command"),
			(args, i) => args.fromPlanFile = i);
		AddOption(new Option<bool>(new[] { "--from-latest-plan", "--latest-plan", "--last-plan", "-lp" }, "Use the most recent plan generated for this bundle from the `bundles plan` command"),
			(args, i) => args.fromLastPlan = i);
		AddOption(new Option<string>(new[] { "--tag" }, "An additional tag to advance to the published checksum"),
			(args, i) => args.tag = i);
		AddOption(new Option<string>(new[] { "--scope" }, "Widen the published checksum's visibility tier (each tier is a superset of the previous, not a list of realms): 'realm' = only this realm; 'org' = every realm in your customer; 'public' = every realm in every customer. A literal <cid>.<pid> / <cid> / * is also accepted"),
			(args, i) => args.scope = i);
	}

	public override async Task Handle(PublishBundleCommandArgs args)
	{
		var provider = args.DependencyProvider;
		var bundle = BundleWorkspace.Require(args.ConfigService, args.bundleName);
		BundleBuild.ValidateComponentsExist(args.BeamoLocalSystem.BeamoManifest, bundle);
		var ns = await BundleNamespace.Get(args);
		var fullName = BundleNamespace.Qualify(ns, bundle.name);
		var bundleApi = provider.GetService<IBeamBeamobundleApi>();

		var isLoadingPlan = !string.IsNullOrEmpty(args.fromPlanFile);
		if (args.fromLastPlan)
		{
			if (isLoadingPlan)
			{
				throw new CliException("cannot specify both --from-latest-plan and --plan");
			}
			args.fromPlanFile = BundlePlanUtil.GetLatestBundlePlanFilePath(provider, bundle.name);
			if (args.fromPlanFile == null)
			{
				throw new CliException(
					$"cannot use --from-latest-plan, because there are no plan files for bundle=[{bundle.name}]. Please run `dotnet beam bundles plan {bundle.name}`");
			}

			isLoadingPlan = true;
		}

		DeployablePlan plan;
		BundleDiffResult diff;
		string plannedAgainstChecksum;
		if (isLoadingPlan)
		{
			Log.Information($"Loading bundle plan from file=[{args.fromPlanFile}]");
			var planFile = await BundlePlanUtil.LoadBundlePlanFile(args.fromPlanFile, bundle.name);
			plan = planFile.plan;
			diff = planFile.diff;
			plannedAgainstChecksum = planFile.publishedChecksum;
		}
		else
		{
			Log.Information($"Generating publish plan for bundle=[{fullName}]...");
			// Don't exclude bundle components here — this command operates on exactly those components.
			// Restrict the build to them, so an unrelated local service can't fail (or slow down) the publish.
			(plan, _) = await this.InteractivePlan(provider, args, excludeAuthoredBundleComponents: false, savePlanToTemp: false,
				includeOnlyBeamoIds: new HashSet<string>(bundle.components));
			diff = null;
			plannedAgainstChecksum = null;
		}

		var (services, storages, extensions) = BundleBuild.SelectComponents(plan, bundle);

		// Diff against the currently-published @latest and show what would change (like `release`).
		var published = await BundleBuild.FetchLatestPublished(bundleApi, ns, bundle.name);
		if (isLoadingPlan)
		{
			// The stored diff is only meaningful against the catalog state it was computed from.
			var currentChecksum = published?.checksum.GetOrElse("") ?? "";
			if (currentChecksum != plannedAgainstChecksum)
			{
				throw new CliException(
					"The given bundle plan was created against a different published version of the bundle than exists now. Please create a new plan and try again.");
			}
		}
		else
		{
			diff = BundleDiff.Compute(services, storages, extensions, published);
			var planPath = await BundlePlanUtil.SaveBundlePlanToTempFolder(provider, new BundlePlanFile
			{
				bundleName = bundle.name,
				publishedChecksum = diff.publishedChecksum,
				plan = plan,
				diff = diff,
			});
			Log.Information("Saved plan: " + planPath);
		}

		BundleDiff.Print(diff, fullName);

		if (diff.isNoOp)
		{
			Log.Information("Nothing to publish.");
			this.SendResults<DefaultStreamResultChannel, PublishBundleCommandOutput>(new PublishBundleCommandOutput
			{
				name = fullName, checksum = diff.publishedChecksum, isNew = false, diff = diff,
			});
			return;
		}

		// Confirm before mutating the catalog (mirrors `deploy release`). --quiet skips the prompt.
		var confirm = args.Quiet || string.Equals("yes",
			AnsiConsole.Prompt(new TextPrompt<string>($"Are you sure you want to publish these changes to {Markup.Escape(fullName)}?\nType 'yes' to continue.")),
			StringComparison.InvariantCultureIgnoreCase);
		if (!confirm)
		{
			Log.Information("Publish cancelled.");
			return;
		}

		// Upload the bundle's changed service images (shared with the realm deploy path).
		var servicesToUpload = new HashSet<string>(plan.servicesToUpload);
		if (services.Any(s => servicesToUpload.Contains(s.serviceName)))
		{
			var gamePid = (await args.RealmsApi.GetRealm()).FindRoot().Pid;
			var dockerRegistryUrl = await args.BeamoService.GetDockerImageRegistryUri();
			await DeployUtil.UploadServiceImages(services, servicesToUpload, provider, gamePid,
				dockerRegistryUrl, args.Lifecycle.Source, null);
		}

		// Upload the bundle's portal-extension assets; this fills each extension's file contentIds
		// on the plan references (which `extensions` points into) before we build the request.
		if (extensions.Count > 0)
		{
			await DeployUtil.UploadPortalExtensionBinaries(plan, provider, null,
				new HashSet<string>(extensions.Select(e => e.name)));
		}

		var request = new PublishBundleRequest
		{
			serviceReferences = new OptionalArrayOfServiceReference
			{
				HasValue = true, Value = services.ConvertToBundleReference()
			},
			storageReferences = new OptionalArrayOfServiceStorageReference
			{
				HasValue = true, Value = storages.ConvertToBundleReference()
			},
		};
		if (extensions.Count > 0)
		{
			request.portalExtensionReferences = new OptionalArrayOfPortalExtensionReference
			{
				HasValue = true, Value = extensions.Select(PortalExtensionPlanReference.ToBundleReference).ToArray()
			};
		}
		if (!string.IsNullOrEmpty(args.tag))
		{
			request.tag = args.tag;
		}

		if (bundle.peerDependencies.Count > 0)
		{
			var map = new MapOfBundlePeerDep();
			foreach (var kvp in bundle.peerDependencies)
			{
				map[kvp.Key] = new BundlePeerDep { type = kvp.Value?.type };
			}

			request.peerDependencies = new OptionalMapOfBundlePeerDep { HasValue = true, Value = map };
		}

		var response = await bundleApi.PostBundlesPublish(bundle.name, ns, request);

		// Response fields are Optional* wrappers — unwrap to their values (don't interpolate the wrapper).
		var publishedName = response.name.GetOrElse(fullName);
		var publishedChecksum = response.checksum.GetOrElse("");
		var isNew = response.isNew.GetOrElse(false);
		Log.Information($"Published bundle=[{publishedName}] checksum=[{publishedChecksum}] isNew=[{isNew}]");

		// Optionally widen the freshly-published checksum's ACL (publish always defaults to <cid>.<pid>).
		if (!string.IsNullOrEmpty(args.scope))
		{
			var scope = BundleAclScope.Resolve(args.scope, args.AppContext);
			await bundleApi.PatchBundlesChecksumsAcl(bundle.name, publishedChecksum, ns, new UpdateBundleAclRequest { scope = scope });
			Log.Information($"Widened ACL for checksum=[{publishedChecksum}] to scope=[{scope}]");
		}

		this.SendResults<DefaultStreamResultChannel, PublishBundleCommandOutput>(new PublishBundleCommandOutput
		{
			name = publishedName,
			checksum = publishedChecksum,
			isNew = isNew,
			diff = diff,
		});
	}
}
