using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Threading;
using UnityEngine;
using UnityEngine.Networking;

namespace Beamable.Notifications.Web
{
    /// <summary>
    /// Tiny embedded HTTP server that serves a static web bundle out of
    /// StreamingAssets on 127.0.0.1, so a WebView can load it with a proper
    /// http origin — no external dev server, no file:// CORS/routing problems,
    /// and it works identically in the Editor, on iOS and on Android (where
    /// StreamingAssets live inside the APK and are not plain files).
    ///
    /// Expects <c>Assets/StreamingAssets/{contentFolder}/</c> to contain the
    /// bundle plus a <c>manifest.txt</c> listing every file (one relative path
    /// per line) — generated by the Web Bundle Exporter (Tools ▸ Beamable ▸ Web Bundle Exporter).
    /// The served folder comes from StreamingAssets/beamable-webview.json (falls back to the
    /// serialized contentFolder field). All files are
    /// loaded into memory up front via UnityWebRequest (the only API that can
    /// read StreamingAssets on every platform), then served from the dictionary.
    /// Unknown extension-less paths fall back to index.html (SPA routing).
    ///
    /// Optional helper: a game may skip this and point its WebView at any URL
    /// (an Expo dev server, a CDN, etc.). The bridge does not depend on it.
    /// </summary>
    public class StreamingAssetsServer : MonoBehaviour
    {
        [SerializeField] private int port = 17890;
        [SerializeField] private string contentFolder = "react";

        public string BaseUrl => $"http://127.0.0.1:{port}/";
        public bool IsReady { get; private set; }

        private readonly Dictionary<string, byte[]> files = new Dictionary<string, byte[]>();
        private HttpListener listener;
        private Thread serverThread;

        private static readonly Dictionary<string, string> MimeTypes = new Dictionary<string, string>
        {
            { ".html", "text/html; charset=utf-8" },
            { ".js", "application/javascript" },
            { ".mjs", "application/javascript" },
            { ".css", "text/css" },
            { ".json", "application/json" },
            { ".map", "application/json" },
            { ".png", "image/png" },
            { ".jpg", "image/jpeg" },
            { ".jpeg", "image/jpeg" },
            { ".gif", "image/gif" },
            { ".svg", "image/svg+xml" },
            { ".ico", "image/x-icon" },
            { ".woff", "font/woff" },
            { ".woff2", "font/woff2" },
            { ".ttf", "font/ttf" },
            { ".wasm", "application/wasm" },
        };

        /// <summary>Loads the bundle into memory and starts listening. Sets IsReady on success.</summary>
        public IEnumerator StartServer()
        {
            // Resolve which folder to serve. A StreamingAssets/beamable-webview.json config (written by
            // the Web Bundle Exporter, and hand-editable) wins; otherwise fall back to the serialized
            // contentFolder field. This keeps the folder name out of the tool and the scene component.
            string configText = null;
            yield return FetchStreamingAsset("beamable-webview.json",
                bytes => configText = bytes != null ? System.Text.Encoding.UTF8.GetString(bytes) : null);
            if (!string.IsNullOrEmpty(configText))
            {
                try
                {
                    var cfg = JsonUtility.FromJson<WebViewConfig>(configText);
                    if (cfg != null && !string.IsNullOrEmpty(cfg.contentFolder)) contentFolder = cfg.contentFolder;
                }
                catch (Exception e)
                {
                    Debug.LogWarning($"[StreamingAssetsServer] Ignoring malformed beamable-webview.json: {e.Message}");
                }
            }

            // Serve the app's Beamable realm at /beam-config.json so the page can resolve it at runtime
            // (the page fetches it and overrides the config baked into the bundle; absent → baked config).
            //   • Editor: read the project's LIVE .beamable/config.beam.json (walk up from the project
            //     root) so Play reflects the current realm without a rebuild.
            //   • Player: read the copy the build preprocessor staged into StreamingAssets.
            // Absent in both → not served (the page's fetch 404s and falls back to the built-in config).
            string beamConfigJson = null;
#if UNITY_EDITOR
            beamConfigJson = BeamWebConfigLocator.ReadConfigJson();
#endif
            if (string.IsNullOrEmpty(beamConfigJson))
            {
                yield return FetchStreamingAsset("beam-config.json",
                    bytes => beamConfigJson = bytes != null ? System.Text.Encoding.UTF8.GetString(bytes) : null);
            }
            if (!string.IsNullOrEmpty(beamConfigJson))
                files["beam-config.json"] = System.Text.Encoding.UTF8.GetBytes(beamConfigJson);

            string manifestText = null;
            yield return Fetch("manifest.txt",
                bytes => manifestText = bytes != null ? System.Text.Encoding.UTF8.GetString(bytes) : null);
            if (manifestText == null)
            {
                Debug.LogError($"[StreamingAssetsServer] Missing StreamingAssets/{contentFolder}/manifest.txt — " +
                               "run the Web Bundle Exporter (Tools ▸ Beamable ▸ Web Bundle Exporter) to export and copy the web bundle.");
                yield break;
            }

            foreach (var rawLine in manifestText.Split('\n'))
            {
                var rel = rawLine.Trim();
                if (rel.Length == 0 || rel == "manifest.txt") continue;
                byte[] data = null;
                yield return Fetch(rel, bytes => data = bytes);
                if (data != null) files[rel] = data;
                else Debug.LogWarning($"[StreamingAssetsServer] Listed in manifest but unreadable: {rel}");
            }

            if (!files.ContainsKey("index.html"))
            {
                Debug.LogError("[StreamingAssetsServer] Bundle has no index.html — not starting.");
                yield break;
            }

            try
            {
                listener = new HttpListener();
                listener.Prefixes.Add(BaseUrl);
                listener.Start();
            }
            catch (Exception e)
            {
                Debug.LogError($"[StreamingAssetsServer] Could not listen on {BaseUrl}: {e.Message}");
                yield break;
            }

            serverThread = new Thread(ServeLoop) { IsBackground = true };
            serverThread.Start();
            IsReady = true;
            Debug.Log($"[StreamingAssetsServer] Serving {files.Count} files at {BaseUrl}");
        }

        private IEnumerator Fetch(string relativePath, Action<byte[]> onDone) =>
            FetchStreamingAsset(Path.Combine(contentFolder, relativePath), onDone);

        /// <summary>Reads a file relative to the StreamingAssets root (works in Editor, iOS and inside the Android APK).</summary>
        private IEnumerator FetchStreamingAsset(string relativePath, Action<byte[]> onDone)
        {
            var path = Path.Combine(Application.streamingAssetsPath, relativePath);
            // On Android streamingAssetsPath is already a jar:file:// URL; elsewhere it's a plain path.
            var url = path.Contains("://") ? path : "file://" + path;
            using (var req = UnityWebRequest.Get(url))
            {
                yield return req.SendWebRequest();
                onDone(req.result == UnityWebRequest.Result.Success ? req.downloadHandler.data : null);
            }
        }

        /// <summary>Shape of StreamingAssets/beamable-webview.json (written by the Web Bundle Exporter).</summary>
        [Serializable]
        private class WebViewConfig
        {
            public string contentFolder;
        }

        private void ServeLoop()
        {
            while (listener != null && listener.IsListening)
            {
                HttpListenerContext ctx;
                try { ctx = listener.GetContext(); }
                catch { break; } // listener stopped

                try { Serve(ctx); }
                catch (Exception e) { Debug.LogWarning($"[StreamingAssetsServer] {e.Message}"); }
            }
        }

        private void Serve(HttpListenerContext ctx)
        {
            var rel = ctx.Request.Url.AbsolutePath.TrimStart('/');
            if (rel.Length == 0) rel = "index.html";

            if (!files.TryGetValue(rel, out var body))
            {
                var lastSegment = rel.Substring(rel.LastIndexOf('/') + 1);
                if (!lastSegment.Contains("."))
                {
                    body = files["index.html"]; // SPA fallback: /details/42 → index.html
                    rel = "index.html";
                }
                else
                {
                    ctx.Response.StatusCode = 404;
                    ctx.Response.Close();
                    return;
                }
            }

            var ext = Path.GetExtension(rel).ToLowerInvariant();
            ctx.Response.ContentType = MimeTypes.TryGetValue(ext, out var mime) ? mime : "application/octet-stream";
            ctx.Response.ContentLength64 = body.Length;
            ctx.Response.OutputStream.Write(body, 0, body.Length);
            ctx.Response.Close();
        }

        private void OnDestroy()
        {
            IsReady = false;
            try { listener?.Stop(); listener?.Close(); } catch { /* shutting down */ }
            listener = null;
        }
    }
}
