
namespace Beamable.Api.Autogenerated.Customersegments
{
    using Beamable.Api.Autogenerated.Models;
    using Beamable.Common.Content;
    using Beamable.Common;
    using IBeamableRequester = Beamable.Common.Api.IBeamableRequester;
    using Method = Beamable.Common.Api.Method;
    using Beamable.Common.Dependencies;
    
    public partial interface IBeamCustomersegmentsApi
    {
        /// <summary>
        /// GET call to `/api/customers/{customerId}/segments/{segmentId}/count` endpoint.
        /// </summary>
        /// <param name="customerId"></param>
        /// <param name="segmentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="SegmentCountResponse"/></returns>
        Promise<SegmentCountResponse> GetSegmentsCount(string customerId, string segmentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// GET call to `/api/customers/{customerId}/segments/{segmentId}/members` endpoint.
        /// </summary>
        /// <param name="cursor"></param>
        /// <param name="customerId"></param>
        /// <param name="segmentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="SegmentMemberInfoCursorPagedResult"/></returns>
        Promise<SegmentMemberInfoCursorPagedResult> GetSegmentsMembers(string customerId, string segmentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> cursor, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
        /// <summary>
        /// GET call to `/api/customers/{customerId}/segments/{segmentId}/members/{playerId}` endpoint.
        /// </summary>
        /// <param name="customerId"></param>
        /// <param name="playerId"></param>
        /// <param name="segmentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="MembershipCheckResponse"/></returns>
        Promise<MembershipCheckResponse> GetSegmentsMembers(string customerId, long playerId, string segmentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader);
    }
    public partial class BeamCustomersegmentsApi : IBeamCustomersegmentsApi
    {
        /// <summary>
        /// GET call to `/api/customers/{customerId}/segments/{segmentId}/count` endpoint.
        /// </summary>
        /// <param name="customerId"></param>
        /// <param name="segmentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="SegmentCountResponse"/></returns>
        public virtual Promise<SegmentCountResponse> GetSegmentsCount(string customerId, string segmentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/customers/{customerId}/segments/{segmentId}/count";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            gsUrl = gsUrl.Replace("{segmentId}", _requester.EscapeURL(segmentId.ToString()));
            // make the request and return the result
            return _requester.Request<SegmentCountResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<SegmentCountResponse>);
        }
        /// <summary>
        /// GET call to `/api/customers/{customerId}/segments/{segmentId}/members` endpoint.
        /// </summary>
        /// <param name="cursor"></param>
        /// <param name="customerId"></param>
        /// <param name="segmentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="SegmentMemberInfoCursorPagedResult"/></returns>
        public virtual Promise<SegmentMemberInfoCursorPagedResult> GetSegmentsMembers(string customerId, string segmentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(null)] [System.Runtime.InteropServices.OptionalAttribute()] Beamable.Common.Content.Optional<string> cursor, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/customers/{customerId}/segments/{segmentId}/members";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            gsUrl = gsUrl.Replace("{segmentId}", _requester.EscapeURL(segmentId.ToString()));
            string gsQuery = "?";
            System.Collections.Generic.List<string> gsQueries = new System.Collections.Generic.List<string>();
            if (((cursor != default(OptionalString)) 
                        && cursor.HasValue))
            {
                gsQueries.Add(string.Concat("cursor=", cursor.Value.ToString()));
            }
            if ((gsQueries.Count > 0))
            {
                gsQuery = string.Concat(gsQuery, string.Join("&", gsQueries));
                gsUrl = string.Concat(gsUrl, gsQuery);
            }
            // make the request and return the result
            return _requester.Request<SegmentMemberInfoCursorPagedResult>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<SegmentMemberInfoCursorPagedResult>);
        }
        /// <summary>
        /// GET call to `/api/customers/{customerId}/segments/{segmentId}/members/{playerId}` endpoint.
        /// </summary>
        /// <param name="customerId"></param>
        /// <param name="playerId"></param>
        /// <param name="segmentId"></param>
        /// <param name="includeAuthHeader">By default, every request will include an authorization header so that the request acts on behalf of the current user. When the includeAuthHeader argument is false, the request will not include the authorization header for the current user.</param>
        /// <returns>A promise containing the <see cref="MembershipCheckResponse"/></returns>
        public virtual Promise<MembershipCheckResponse> GetSegmentsMembers(string customerId, long playerId, string segmentId, [System.Runtime.InteropServices.DefaultParameterValueAttribute(true)] [System.Runtime.InteropServices.OptionalAttribute()] bool includeAuthHeader)
        {
            string gsUrl = "/api/customers/{customerId}/segments/{segmentId}/members/{playerId}";
            gsUrl = gsUrl.Replace("{customerId}", _requester.EscapeURL(customerId.ToString()));
            gsUrl = gsUrl.Replace("{segmentId}", _requester.EscapeURL(segmentId.ToString()));
            gsUrl = gsUrl.Replace("{playerId}", _requester.EscapeURL(playerId.ToString()));
            // make the request and return the result
            return _requester.Request<MembershipCheckResponse>(Method.GET, gsUrl, default(object), includeAuthHeader, this.Serialize<MembershipCheckResponse>);
        }
    }
}
