using Beamable.Api.Autogenerated.Beamopullrequest;
using Beamable.Api.Autogenerated.Models;
using Beamable.Server;
using System.CommandLine;

namespace cli;

public class PrCommentCommandArgs : CommandArgs
{
	public string Id;
	public string Message;
}

public class PrCommentCommandOutput
{
	public string id;
}

public class PrCommentCommand : AtomicCommand<PrCommentCommandArgs, PrCommentCommandOutput>, ISkipManifest
{
	public PrCommentCommand() : base("comment", "Append a comment to a pull request's discussion thread")
	{
	}

	public override void Configure()
	{
		AddOption(new Option<string>("--id", "The id of the pull request to comment on"),
			(args, i) => args.Id = i);
		AddOption(new Option<string>(new[] { "--message", "-m" }, "The comment to append to the discussion thread"),
			(args, i) => args.Message = i);
	}

	public override async Task<PrCommentCommandOutput> GetResult(PrCommentCommandArgs args)
	{
		if (string.IsNullOrEmpty(args.Id))
		{
			throw new CliException("--id is required. Use --id <pullRequestId> to specify the pull request to comment on.");
		}
		if (string.IsNullOrWhiteSpace(args.Message))
		{
			throw new CliException("--message is required and cannot be empty. Use -m \"<text>\" to provide the comment.");
		}

		var request = new CommentPullRequestRequest { message = args.Message };
		var api = args.Provider.GetService<IBeamBeamopullrequestApi>();
		await api.PostPrsComments(args.Id, request);

		return new PrCommentCommandOutput { id = args.Id };
	}
}
