// this file was copied from nuget package Beamable.Server.Common@0.0.0-PREVIEW.NIGHTLY-202407161549
// https://www.nuget.org/packages/Beamable.Server.Common/0.0.0-PREVIEW.NIGHTLY-202407161549

using Beamable.Api.Autogenerated.Models;
using Beamable.Common;
using Beamable.Common.Api.Push;

namespace Beamable.Server.Api.Push
{
	public interface IMicroservicePushApi : IPushApi
	{
		/// <summary>
		/// Send messages to subscribed players. 
		/// </summary>
		/// <param name="messages"></param>
		/// <returns></returns>
		Promise Push(params SendMsg[] messages);
	}
}
