name: Docs PR

on:
  pull_request:
    branches:
      - 'main'
    # paths:
    #   - 'client/**'
    #   - 'microservice/**'

jobs:
  doxygen:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    concurrency:
      group: doxygen-${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: mattnotmitt/doxygen-action@v1.9.2
        name: Doxygen
        with:
          additional-packages: graphviz
          doxyfile-path: 'client/Doxyfile'
      - name: ls a
        run: |
          ls -a
        shell: bash
      - name: ls r
        run: |
          ls -R
        shell: bash
      - name: Archive
        run: |
          tar cfz docs-html.tar.gz ./html'
        shell: bash
      - uses: actions/upload-artifact@v2
        name: Keep Artifact
        if: always()
        with:
          path: docs-html.tar.gz
          retention-days: 3
      - name: Upload to S3
        run: AWS_ACCESS_KEY_ID=${{secrets.AWS_KEY_ID}} AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} AWS_REGION=us-west-2 aws s3 sync --delete html/ s3://${{secrets.S3_DOCS_BUCKET}}/DEV/
      # - name: Invalid Cloudfront Cache
      #   run: AWS_ACCESS_KEY_ID=${{secrets.AWS_KEY_ID}} AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} AWS_REGION=us-west-2 aws cloudfront create-invalidation --cli-input-json file://${commandFile}