name: Docs PR

on:
  pull_request:
    branches:
      - 'main'
    # paths:
    #   - 'client/**'
    #   - 'microservice/**'

jobs:
  doxygen:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    concurrency:
      group: doxygen-${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: mattnotmitt/doxygen-action@v1.9.2
        with:
          additional-packages: graphviz
          doxyfile-path: 'client/Doxyfile'
      - name: Archive docs
        run: |
          tar cfz docs-html.tar.gz ./html'
        shell: bash
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          path: docs-html.tar.gz
          retention-days: 3