name: Docs CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'client/**'
      - 'microservice/**'

jobs:
  doxygen:
    uses: Beamable/BeamableProduct/.github/workflows/docsCommon.yml@main
    with:
      s3Dest: DEV
    secrets:
      AWS_KEY_ID: ${{secrets.AWS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      S3_DOCS_BUCKET: ${{secrets.S3_DOCS_BUCKET}}