name: Docs Tag

on:
  push:
    tags:
      - '1.**'
      - '!1.**-PREVIEW**'
      - '!0.**'

jobs:
  doxygen:
    uses: Beamable/BeamableProduct/.github/workflows/docsCommon.yml@main
    with:
      s3Dest: ${GITHUB_REF#refs/*/}
      