name: Docs Tag

on:
  push:
    tags:
      - '1.**'
      - '!1.**-PREVIEW**'
      - '!0.**'

jobs:
  doxygen:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    concurrency:
      group: doxygen-${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - name: Identify Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check Tag
        run: echo ${{ steps.vars.outputs.tag }}
      # - uses: beamable/BeamableProduct/.github/workflows/docsCommon.yml@main
      #   name: Build Docs
      #   with:
      #     s3Dest: ${{ steps.vars.outputs.tag }}
      