name: Docs CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'client/**'
      - 'microservice/**'

jobs:
  doxygen:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    concurrency:
      group: doxygen-dev-${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/docsCommon.yml@main
        name: Build Docs
        with:
          s3Dest: DEV
      