name: Lint Markdown

on:
  pull_request:
    branches:
      - 'main'
      - 'staging'
      - 'production'

jobs:
  lint-markdown:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    concurrency:
      group: lint-markdown-${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: 'rfc/*.md'
