name: Test

on: 
 push:
  branches:
    - 'main'
  paths:
    - 'client/**'
    - 'microservice/**'
 pull_request:
  branches:
    - 'main'
    - 'staging'
  paths:
    - 'client/**'
    - 'microservice/**'

jobs:
  code-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1
      - name: Restore dotnet tools
        uses: xt0rted/dotnet-tool-restore@v1
      - name: Run dotnet format
        uses: xt0rted/dotnet-format@v1
        with:
          only-changed-files: "true"
