name: Test

on: 
 push:
  branches:
    - 'main'
    - 'iOS'
 pull_request:
  branches:
    - 'main'
    - 'staging'
    - 'iOS'
jobs:
  testMicroserviceBaseImage:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    concurrency: 
      group: base-image-tests-${{ github.head_ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Install dependencies
        run: dotnet restore microservice/microserviceTests
      - name: Build
        run: dotnet build --configuration Release --no-restore microservice/microserviceTests
      - name: Test
        uses: zyborg/dotnet-tests-report@v1
        with:
          set_check_status_from_test_outcome: true
          project_path: microservice/microserviceTests
          report_name: Microservice_base_image_tests
          report_title: Microservice Base Image Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: macos-latest
    timeout-minutes: 60
    concurrency: 
      group: device-builds-${{ matrix.targetPlatform }}-${{ github.head_ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS
        unityVersion:
          - 2020.3.19f1
        projectPath:
          - client
    steps:
      #Build iOS
      - uses: actions/download-artifact@v2
        with:
          name: Build-iOS
      - name: Change directory to the location of the xcode project
        run: cd iOS/
      - uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: Unity-iPhone.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.PROD_MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}