name: Test

on: 
 push:
  branches:
    - 'main'
    - 'iOS'
 pull_request:
  branches:
    - 'main'
    - 'iOS'
jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency: 
      group: device-builds-test-${{ matrix.targetPlatform }}-${{ github.head_ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS
        unityVersion:
          - 2020.3.19f1
        projectPath:
          - client
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prepare Config-Defaults
        run: |
          chmod +x ./build/create_config_defaults.sh
          ./build/create_config_defaults.sh
        shell: bash
      - name: Check Unity IAP
        run: |
          chmod +x ./build/clean_iap.sh
          UNITY_VERSION=${{ matrix.unityVersion }} ./build/clean_iap.sh
        shell: bash
      - name: Check Gradle Builds
        run: |
          chmod +x ./build/clean_gradle.sh
          UNITY_VERSION=${{ matrix.unityVersion }} ./build/clean_gradle.sh
        shell: bash
      - name: Cache Docker Layers
        uses: actions/cache@v2
        id: cache_docker
        with:
          path: ./docker-cache
          key: Docker-gzipped-${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Docker-gzipped-${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}
      - name: Load Docker Image If Exits
        if: ${{ steps.cache_docker.outputs.cache-hit }}
        continue-on-error: true
        run: |
          chmod +x ./build/prepare_base_image.sh
          UNITY_VERSION=${{ matrix.unityVersion }} TARGET_PLATFORM=${{matrix.targetPlatform}} ./build/prepare_base_image.sh
        shell: bash
      - name: Cache Unity Folders
        uses: actions/cache@v2
        with:
          path: |
            ${{ matrix.projectPath }}/Library
            ${{ matrix.projectPath }}/Temp
            ${{ matrix.projectPath }}/obj
          key: Library-${{ matrix.projectPath }}-${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}
      - uses: game-ci/unity-builder@v2
        timeout-minutes: 30
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ matrix.unityVersion }}
          projectPath: ${{ matrix.projectPath }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          versioning: Semantic
          allowDirtyBuild: true
          buildsPath: dist

      - name: Save Docker Image If Exits
        if: ${{ !steps.cache_docker.outputs.cache-hit }}
        run: |
          chmod +x ./build/save_base_image.sh
          UNITY_VERSION=${{ matrix.unityVersion }} TARGET_PLATFORM=${{matrix.targetPlatform}} ./build/save_base_image.sh
        shell: bash
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.targetPlatform != 'WebGL' }}
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: dist/${{ matrix.targetPlatform }}
          retention-days: 3

  ios:
    name: Build for iOS .ipa and upload to Testflight
    runs-on: macos-latest
    timeout-minutes: 30
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: Build-iOS
      - name: Change directory to the location of the xcode project
        run: cd iOS/
      - uses: yukiarrr/ios-build-action@v1.4.0
        with:
          update-targets: Unity-iPhone
          project-path: ${{ secrets.XCODEPROJ_PATH }}
          p12-key-path: ${{ secrets.P12_KEY_PATH }}
          p12-cer-path: ${{ secrets.P12_CER_PATH }}
          certificate-password: ${{ secrets.P12_PASSWORD }}
          mobileprovision-path: /Users/runner/work/BeamableProduct/BeamableProduct/build/ios/BeamableProductProd.mobileprovision
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: A6C4565DLF