name: Test

on: [push, pull_request]


jobs:
  testAllModes:
    name: Tests ${{ matrix.unityVersion }} ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - client
        testMode:
          - playmode
          - editmode
        unityVersion:
          - 2018.4.18f1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ${{ matrix.projectPath }}/Library
            ${{ matrix.projectPath }}/Temp
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-${{ matrix.projectPath }}

      # - uses: game-ci/unity-test-runner@v2
      #   id: tests
      #   env:
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #     UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      #   with:
      #     projectPath: ${{ matrix.projectPath }}
      #     testMode: ${{ matrix.testMode }}
      #     unityVersion: ${{ matrix.unityVersion }}
      #     artifactsPath: ${{ matrix.testMode }}-artifacts
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}
      #     checkName: ${{ matrix.unityVersion }} ${{ matrix.testMode }} Test Results
      # - uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: Test results for ${{ matrix.unityVersion }} ${{ matrix.testMode }}
      #     path: ${{ steps.tests.outputs.artifactsPath }}