name: Confluence Update

on:
  push:
    branches:
      - 'main'
      - 'feature/platformDocs'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Publish Markdown to Confluence
        uses: markdown-confluence/publish@v1
        with:
          confluenceBaseUrl: https://disruptorbeam.atlassian.net
          confluenceParentId: 2947842049
          atlassianUserName: "piotr@beamable.com"
          atlassianApiToken: "ATATT3xFfGF0AK3pH5a3NaS-110Gded4sjKlR0Np6lDQX_QVIttERUslhjCOqb9vvqdl01Ob8HZ0uzbGijKQGpUipDT_x5NeVivX1JKYhA-DECTeJHgt_NU1ssqHtjGboGPcegPolPQ69NaXVvOVPbnns-Soj-AElsxnL5cawKlu0E6YwJnDNeQ=DE6076B8"
          folderToPublish: platformDocs
          contentRoot: /platformDocs
          configFile: /platformDocs/.markdown-confluence.json