name: Confluence Update

on:
  push:
    branches:
      - 'main'

jobs:
  create-preview:
    runs-on: ubuntu-latest
    name: Uploading Preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Conversion step
        uses: TTengs/MarkdownToConfluence@v3
        with:
            fileslocation: 'platformDocs'
            confluence_url: 'https://disruptorbeam.atlassian.net/wiki'
            confluence_space_key: 'PD'
            auth_username: ${{ secrets.CONFLUENCE_AUTH_USERNAME }}
            auth_api_token: ${{ secrets.CONFLUENCE_AUTH_API_TOKEN }}
            is_preview: false
            should_upload: true