name: Trigger Nightly Release (bot)

on:
  schedule:
    # at 10pm UST (6pm EST), every day.
    - cron: "0 22 * * *"

    # every 30 minutes (debug mode)
    # - cron: "*/30 * * * *"

run-name: Nightly Release Trigger
jobs:
  trigger:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    concurrency:
      group: release-nightly
      cancel-in-progress: true
    steps:
      - name: Create CLI Nightly
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: release-nuget.yml
          inputs: '{ "releaseType": "nightly", "dryRun": false, "major": "0", "minor": "0", "patch": "0" }'
      - name: Create Unity Nightly
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: release-unity.yml
          inputs: '{ "releaseType": "nightly", "dryRun": false, "major": "0", "minor": "0", "patch": "0" }'
