name: Sync Wiki

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  syncDocs:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    concurrency:
      group: sync-docs-${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "wiki"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}